### ISSUE TITLE
Autocomplete suggestions keeps turning off

### ISSUE THREAD

**Issue by 9z0** [ransome1/sleek#130] opened 2021-05-28 00:32 UTC
Since v1.0.3, I have been having trouble with autocomplete for projects and contexts. The suggestion popup doesn't appear

I have a big list (>1000 items), so it is difficult for me to make a good reproduction guide since I am not sure what triggers this.

However, I noticed the following, which may be relevant:
- If I delete `user-preferences.json`, the popup appears again.
    - Then, if I don't click a suggestion but press `Esc`, the edit box closes but the suggestions box remains floating on top of the todo list.
![aa](https://user-images.githubusercontent.com/78097210/119912139-22b2bb80-bf5b-11eb-87eb-dab36034ee1e.png)

- It may have to do with one of these:
`suggestionContainer":true,"selectedFilters":[],"autoCompleteContainer":true`
- Before I deleted the json file, I tried setting autoCompleteContainer to true, but it would revert to false on the following launch.
- Sometimes, selectedFilters is shown like this (with quotes around the brackets): `"selectedFilters":"[]",`.
- I have over 100 projects.
- A trigger, among others, _may_ have been expanding the edit box. (`useTextarea`?) or using Priority filters.
- Some of the options are negative: `"horizontal":-8,"vertical":-8`.

Sorry this is a bit messy. I hope it helps.

**Desktop (please complete the following information):**
 - Windows 10
 - Version of sleek: 1.0.4
 - Source: Github.

**Comment by ransome1** [comment] 2021-05-28 08:27
@9z0, I found a glitch in the autocomplete function connected with the switch between textarea and text field, as you pointed out. I am not sure though, if this solves your issue. Please check this development version if the issue still occurs: https://github.com/ransome1/sleek/releases/tag/v1.0.5-2

**Comment by 9z0** [comment] 2021-05-28 09:23
Seems alright. Thanks.

But I have to try it out for some time to be sure :)

**Comment by ransome1** [comment] 2021-06-01 07:10
@9z0, should also be fixed in https://github.com/ransome1/sleek/releases/tag/v1.0.5. Can you please close here, if the issue is fixed? Thanks :)

**Closed** 2021-06-01 09:41 UTC
Labels: bug
