### ISSUE TITLE
When typing in the top bar, make Ctrl+Enter add the item (same as clicking "+ Add as todo")

### ISSUE THREAD

**Issue by DeflateAwning** [ransome1/sleek#545] opened 2023-10-13 22:57 UTC
Version: v1.3.1

## Description:
I would like to request the addition of a keyboard shortcut to streamline the process of adding items in the top bar of the app. Specifically, I propose that pressing Ctrl+Enter should have the same function as clicking "+ Add as todo." This feature will make it quicker and more efficient for users to add items to their to-do list or other lists.

## Use Case:
This feature would be highly beneficial for users who frequently add items to their lists in the app. Instead of reaching for the mouse and clicking the "+ Add as todo" button, users could simply type the item they want to add and then press Ctrl+Enter to instantly add it. This not only saves time but also provides a more fluid and seamless user experience.

## Implementation Details:
To implement this feature, the development team can follow these steps:

Add a keyboard event listener to the input field in the top bar.
When the user presses Ctrl+Enter, trigger the same action as clicking the "+ Add as todo" button.
Ensure that this functionality is clearly documented in the app's user guide or keyboard shortcut reference.

## Additional Context:
Keyboard shortcuts are a valuable feature for power users and those who prefer a more keyboard-centric approach to using the app. This addition would enhance the overall user experience and make the app more efficient to use. It's a small but meaningful improvement that can have a positive impact on user productivity.

## Important Note:
Please consider implementing this feature to improve the app's usability and efficiency. Keyboard shortcuts are a standard feature in many applications and can greatly enhance the user experience.

**Comment by ransome1** [comment] 2023-10-18 18:28
This is neither a proper feature request. Could you please stick to the template, which is provided?

**Comment by DeflateAwning** [comment] 2023-10-18 18:47
Updated the original ticket!

**Comment by ransome1** [comment] 2023-10-30 20:53
@DeflateAwning released as part of `2.0.0`.

**Closed by ransome1** 2023-10-30 20:53 UTC
Labels: feature request

**Comment by dnngll** [comment] 2024-01-04 15:06
Hi @ransome1 ,

2 suggestions:

- Could this shortcut be added in the "Add a new todo"-field as well? I tried every modifier key + enter, it didn't work. Right now I have to `shift-tab, enter`, or use the mouse. Am I missing something here?
- After entering a new todo via "Find", either (chooseable in settings)
  - refresh/update the ToDo-list below. Right now it is only refreshed when deleting or adding a character in the find-field, OR
  - clear search results and go back to the main list - maybe scroll to the new todo and highlight it for a few moments?

Thanks!

**Comment by ransome1** [comment] 2024-01-04 20:23
> Could this shortcut be added in the "Add a new todo"-field as well? I tried every modifier key + enter, it didn't work. Right now I have to `shift-tab, enter`, or use the mouse. Am I missing something here?

You're right, on Windows and Linux systems this shortcut is missing. I only implemented it in the Mac releases. Here it is `CMD & Enter`. The respective shortcut for Windows and Linux will be added to the next release.

> refresh/update the ToDo-list below. Right now it is only refreshed when deleting or adding a character in the find-field, OR

When you add a new todo using the search textfield, the list will refresh itself. This should already work in almost all previous version, so maybe I need more details here.

The upcoming flow (implemented as part of 2.0.5) is:
- enter something in search textfield
- This will most likely empty the list
- either click the button or use the keyboard shortcut to add it
- the previously entered search string will persist in the textfield, as will the focus
- the list will reload, but since the search string is still present, you will only see the newly created todo
- since the focus is still in the textfield, pressing escape will clear the search textfield and the list will be fully available again

**Comment by dnngll** [comment] 2024-02-20 18:28
Hello @ransome1 ,

I was gone for the past couple of weeks, thanks for your patience. I just updated to `2.0.10-rc.1` and:

> You're right, on Windows and Linux systems this shortcut is missing. I only implemented it in the Mac releases. Here it is `CMD & Enter`. The respective shortcut for Windows and Linux will be added to the next release.

This is working now, thanks!

> When you add a new todo using the search text field, the list will refresh itself. This should already work in almost all previous version, so maybe I need more details here.

There must have been a bug on the version I was using back then. Pressing CTRL-F, typing "test", pressing TAB, SPACE/ENTER left me with an empty list. Only after deleting the last character OR adding any extra character and then deleting it in the find-field, the todo showed below.

It did not happen again when I tested it today, I could not reproduce it. I will report back here if it happens again.

Thanks : )
