### ISSUE TITLE
Window scaling

### ISSUE THREAD

**Issue by shulist** [ransome1/sleek#71] opened 2021-03-22 16:55 UTC
I cannot size the Sleek window to a size that is appropriate for me. It seems you have set the minimum window size and of course I cannot get it to be any smaller. For me at the smallest size the window is mostly empty space and way too large for my screen layout.  See attached photo. For comparison, in the image I have included the todotxt.net application (Font is Verdana 10), I had used in the past--that's the size it typically is on my screen which is about 1/3 of the screen real estate that Sleek's smallest window take up.
![SleekScreen](https://user-images.githubusercontent.com/6595819/111998497-6ff55580-8af2-11eb-8591-54b41d73cdb3.png)

Perhaps the window scaling in combination with the Font Scaling #57 will allow the user to adjust the Sleek window and layout to their liking.

**Comment by ransome1** [comment] 2021-03-22 17:34
Hi @shulist. Removing the minimum window size is not a problem. The big challenge will be to optimize the view for those small sizes, especially the ones on default font-size.

However I removed the min window width barrier and added a first set of CSS optimizations, both are included in this Beta release: https://github.com/ransome1/sleek/releases/tag/v0.9.7-Beta

I will appreciate your feedback.

**Comment by shulist** [comment] 2021-03-22 18:25
@ransome1 That is just great. The adjustable size works well. Good work there!

> optimize the view for those small sizes, especially the ones on default font-size.

I think if you allow for an option of **default Font size** then the user can manipulate the settings on their own to adjust as I would. 

I actually switched to 'Light Mode" and Free Sans is even more unreadable in that mode, especially with colored backgrounds (projects, contexts). I am not sure how wedded you are to Free Sans but there are some fonts that are optimized for screen reading, Verdana being one of those but there are a number of others. That, however, may be a moot point if you allow for use of the users default font.

One other suggestion to recover some screen space would be to move the "View" menu to the left menu perhaps using an icon like a magnifying glass, and then allow the user to hide the left menu if not required? IMO having it there is consistent since, for example, your filter menu is already there. It may be redundant (possibly confusing)to have two different locations to go to to for settings.

Also one other thing that happens when you reduce the screen size--it seems the word wrap begins long before its actually required.

**Comment by ransome1** [comment] 2021-03-22 18:42
FreeSans is a great open source based font, which I like and want to support and so far I haven't had any problems with it, neither on Arch Linux, Ubuntu nor on MacOS.

Maybe it doesn't play well with Windows and if it turns out to be the problem for other Windows users too, I could think about switching to Arial. Both Arial and FreeSans are based on Helvetica if I'm not mistaken and that could be a fit. But can you give me a bit more detail on what exactly is the issue with FreeSans on Windows? Do you have some high res screenshots?

Also I am not sure what you mean by default font size. Do you mean the default font size of the operation system?

**Comment by shulist** [comment] 2021-03-22 18:45
> Do you mean the default font size of the operation system?

Yes, the font and font size set by the Windows user was what I mentioned.

**Comment by ransome1** [comment] 2021-03-24 12:55
Window scaling function has been released as part of 0.9.7

**Closed by ransome1** 2021-03-24 12:55 UTC
Labels: enhancement, feature request

**Comment by ransome1** [comment] 2021-03-24 12:57
@shulist. Feel free to open a separate issue for the font issue. I took a look into my Windows 10 virtual machine and could not really reproduce any issues with FreeSans. So if we work on the font issue, it would be good, if you could provide more details and maybe even screenshots that show, what we need to optimize is.

**Comment by intrepidsilence** [comment] 2021-03-24 18:42
I don't see the font issue being described on Windows. The font is very legible to me in both light and dark modes, even with the wonderful zoom feature being used to make the font tiny. Even the 'bubbles' are clear for me in both modes. I wonder if @shulist could post a screenshot of the issue to make it more clear?

**Comment by shulist** [comment] 2021-04-16 14:50
@ransome1 Just to close this off finally. I now have managed to test out Sleek 0.9.9 on my UHD display and with a few adjustments on my end this version now displays wonderfully. The scaling works well and adjusting the font size down to 75% makes it perfectly readable on either white or black background. **Again a great job done on your part.**

**Comment by ransome1** [comment] 2021-04-16 19:06
@shulist, thanks for your feedback.
