### ISSUE TITLE
Internationalization of Date Picker

### ISSUE THREAD

**Issue by qalisto** [ransome1/sleek#304] opened 2021-12-15 00:05 UTC
Date Picker: for most of world Monday is day #1.
 
 For all people in UK, France, Germany, Russia calendars are configured this way.

Please create option so that popup Month enables also Monday as first day of week.

Indeed, if Rob would really like to enhance temporalization, add a column to the LEFT of the Monday that indicates the "Week Number".  

Many people also use that.  In this case, the input could be wkdue:51 and the app would calculate to the correct 20 Dec 2021 Monday which is the beginning of WK51 by international standard.  OR  in the same way that the T: threshold feature was enabled, maybe the entire TDT system could be improved in this way.  I myself will often task according to Week as an increment of Time.

Thanks for great work thus far!

**Comment by ransome1** [comment] 2021-12-15 06:03
Hi @qalisto thanks for reporting this. 

I think this is a general misconfiguration on my side (for at least the English version, if you switch to German Monday will be 1st day of the week -> Default config of the picker) of the date picker. I intended to have Monday as the first day of the week as a default. I tweaked the date pickers config a bit and in the next release of sleek this will look like this for all users (week numbers included):
<img src="https://user-images.githubusercontent.com/11188741/146131266-5e2246c4-1136-4bef-97e1-fa92288d4856.png" width=300>

I actually don't think there will be users who will be bothered about this change. This is why I don't consider adding a setting for this and bloating the UI for something rarely anybody would make use of.

About your proposal of adding a calender week attribute: Considering the little time I have to work on sleek at the moment, I don't think this will be a priority any time soon. But we can change this feature request and describe how a proper implementation of this new attribute would look and work like. It would then be part of the backlog.

**Comment by ransome1** [comment] 2021-12-15 07:42
@qalisto You can test this in this pre-release: https://github.com/ransome1/sleek/releases/tag/v1.1.4-rc.6

It's going to be part of 1.1.4 which I will propably release today.

**Comment by qalisto** [comment] 2021-12-17 05:34
I see it in my update.  Looking good!  Thanks, much!!

**Comment by dragonDScript** [comment] 2021-12-30 21:05
> Hi @qalisto thanks for reporting this. 
> 
> I think this is a general misconfiguration on my side (for at least the English version, if you switch to German Monday will be 1st day of the week -> Default config of the picker) of the date picker. I intended to have Monday as the first day of the week as a default. I tweaked the date pickers config a bit and in the next release of sleek this will look like this for all users (week numbers included):
> <img src="https://user-images.githubusercontent.com/11188741/146131266-5e2246c4-1136-4bef-97e1-fa92288d4856.png" width=300>
> 
> I actually don't think there will be users who will be bothered about this change. This is why I don't consider adding a setting for this and bloating the UI for something rarely anybody would make use of.
> 
> About your proposal of adding a calender week attribute: Considering the little time I have to work on sleek at the moment, I don't think this will be a priority any time soon. But we can change this feature request and describe how a proper implementation of this new attribute would look and work like. It would then be part of the backlog.

Will it look like this for US people? I think it's important to respect whatever people is used to.

**Comment by ransome1** [comment] 2021-12-30 21:07
Yes, but I can't follow. Can you please describe what the issue is?

**Comment by qalisto** [comment] 2021-12-30 21:49
I think Dragon asks for an option for either Mon start of week or Sun.

Sun start is a non-scientific default for US population.

I would argue that if you can do only one option, honor the overwhelming international standard, which is MONDAY.

The US also still doesn't widely use the METRIC system.  A stupid reflection of arrogance that costs the US economy and businesses by creating international measurement confusion and loss of time due to re-calculation. ###

**Comment by dragonDScript** [comment] 2021-12-31 10:49
> I think Dragon asks for an option for either Mon start of week or Sun.
> 
> Sun start is a non-scientific default for US population. Many in US are used to this. (Like the English measurements systems.)
> 
> I would argue that if you can do only one option, honor the overwhelming international standard, which is MONDAY.
> 
> The US also still doesn't widely use the METRIC system. A stupid reflection of arrogance that costs the US economy and businesses by creating international measurement confusion and loss of time due to re-calculation. ###

Yes, I wanted to said that. You might want to take a look at lost-design/linked, the author's implemented both the US and the international system.

**Comment by swantzter** [comment] 2023-09-18 07:55
@ransome1 I might have things misconfigured, but I think this has regressed in 2.x?

**Comment by ransome1** [comment] 2023-09-24 16:34
@qalisto @qalisto @katuak This should be fixed in the upcoming developer preview `dev13`. I'd appreciate if you guys could be helping out testing it.

**Comment by ransome1** [comment] 2023-09-26 20:44
@qalisto @katuak @swantzter could you guys please check, if this issue still occurs in the [latest developer preview](https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev13)? It should be fixed.

**Comment by swantzter** [comment] 2023-09-26 20:46
@ransome1 i tried to check yesterday but had some issues running it om de mode on my setup, probably haven't gotten WSLg configured right on that machine.
I'll take a look in the developer preview build as soon as I'm back in office on Thursday.

**Comment by ransome1** [comment] 2023-09-28 09:34
> @ransome1 no, I'm still seeing it start on Sunday in -dev13 ![image](https://user-images.githubusercontent.com/10356719/271214768-068ab7c5-98eb-4b13-a2f0-8e6eb04aee19.png)

What is your locale?

**Comment by swantzter** [comment] 2023-09-28 11:49
I can add that i tested this with both English and German as the locale set in sleek (I don't speak german), but regardless I don't think this should be linked to the locale if it is (I want my sleek in English). My computer locales are set to en-GB (prio 1) and sv-SE (prio 2)

**Comment by ransome1** [comment] 2023-10-10 19:56
Well, as far I understand we need to link it to the users locale. How else is this suppose to work?

**Comment by swantzter** [comment] 2023-10-10 21:33
I would suggest a setting for "week starts on", or you'll basically have to add multiple "English" locales like en-US, en-GB, en-SE... or go with ISO 8601 which states the week starts on Monday, but that wouldn't really match how some people operate.

I mean start of the week generally varies between Monday, Friday, Saturday and Sunday across the world, there is data about it in the unicode CLDR i believe, but I also don't think you have access to the fw field in Intl.Locale in js

**Comment by ransome1** [comment] 2023-10-14 06:05
The way the date picker ([React MUI Date picker](https://mui.com/x/react-date-pickers/)) works is by locale. There are some deprecated ways of manually settings the first day of the week, but I couldn't get them to work and the offical documentation of the datepicker doesn't mention those anyways.

In sleek we're using `dayjs` for the localization and the `en` locale (the locale files, not the translations, are provided by `dayjs`) defaults to Sunday to be the first day of the week. If we want to change this, we need to provide the datepicker with a locale, that sets Monday as the first day of the week. Since this is the case in the UK, we can provide the datepicker with `en-gb` in order to achieve this.

Thus the only feasible solution I can think of at the moment is to introduce a new language setting `English (UK)`. Selecting English (UK) reliably changes the first day of the week to Monday by maintaining the interface to be translated in English.

![Image](https://github.com/ransome1/sleek/assets/11188741/f4317f76-347f-408c-8556-92b79739410e)

I'm open to other solid suggestions.

**Comment by ransome1** [comment] 2023-10-15 08:48
> The way the date picker ([React MUI Date picker](https://mui.com/x/react-date-pickers/)) works is by locale. There are some deprecated ways of manually settings the first day of the week, but I couldn't get them to work and the offical documentation of the datepicker doesn't mention those anyways.
> 
> In sleek we're using `dayjs` for the localization and the `en` locale (the locale files, not the translations, are provided by `dayjs`) defaults to Sunday to be the first day of the week. If we want to change this, we need to provide the datepicker with a locale, that sets Monday as the first day of the week. Since this is the case in the UK, we can provide the datepicker with `en-gb` in order to achieve this.
> 
> Thus the only feasible solution I can think of at the moment is to introduce a new language setting `English (UK)`. Selecting English (UK) reliably changes the first day of the week to Monday by maintaining the interface to be translated in English.
> 
> ![Image](https://user-images.githubusercontent.com/11188741/275151557-f4317f76-347f-408c-8556-92b79739410e.png)
> 
> I'm open to other solid suggestions.

This can be tested in https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev16

**Comment by swantzter** [comment] 2023-10-17 14:28
works for me :)

**Closed** 2023-10-18 19:11 UTC
Labels: feature request

**Comment by qalisto** [comment] 2023-12-23 01:30
@ransome1 -
Apologies for disappearing.
I often get severely distracted by other projects ... for weeks.  
:O
