### ISSUE TITLE
Light theme is incorrectly used for UI but not for window host as "follow system" after updates

### ISSUE THREAD

**Issue by swantzter** [ransome1/sleek#530] opened 2023-09-28 08:26 UTC
## Bug Report

**IMPORTANT:**
Please follow this template strictly when reporting bugs. Providing detailed and accurate information helps the development team to understand and address the issue effectively.

**App Version:** 2.0.0-dev10, 2.0.0-dev11, 2.0.0-dev12, 2.0.0-dev13

**Platform:** Windows

**Installation Method:** Direct Download

**Bug Description:**
Probably related to #529, but may also happen on first clean install, the theme in settings is set to "follow system", the windows elements like the program window and menu bar is in dark mode but sleek's UI is in light mode. Changing the setting to "Dark" does nothing, changing the setting to "Light" and then "Dark" fixes the problem

**Steps to Reproduce:**
1. Update sleek 2.0.0-dev12 to 2.0.0-dev13 when your theme is set to dark

**Expected Behavior:**
The theme will be dark throughout after the update, or changing from "follow system" to dark in settings will change the theme

**Actual Behavior:**
The UI theme is reverted to light, changing to "dark" in settings does nothing

**Additional Information:**

**Screenshots:**

**System Information:**
- OS Version: Windows 11
- Processor: Intel Core i7
- RAM: 32GB
- Graphics Card: NVIDIA GeForce GTX 1650 Ti

**Reproducibility:**
- Always

**Impact:**
- Minor

**Workaround:**
Changing the theme to light and then back to dark or follow system fixes the theme

**Comment by ransome1** [comment] 2023-09-28 09:38
This has been fixed in a commit yesterday. It will be available in the next dev preview.

**Comment by ransome1** [comment] 2023-09-29 11:46
@swantzter Could you check of this still occurs in https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev14?

**Comment by swantzter** [comment] 2023-09-29 12:01
Yes, here is a demo I started recording immediately after opening -dev14 for the first time:
https://github.com/ransome1/sleek/assets/10356719/873971e1-884a-479a-bd6c-2db97529f43f

**Comment by ransome1** [comment] 2023-09-29 12:50
@swantzter so when you're starting sleek, your OS is in dark mode and sleek's window frame is already in dark mode, but the application is still in light mode, right? And then there is some weird thing going on with the selection. 

That's very interesting, because I simply do not have this behavior here on a Mac. I'm now a couple of days offline but when I'm back, I have access to a Windows system. Hopefully I can reproduce it there.

This will most likely be some small thing, but what worries me more is the empty language field. You don't see any language names in that select box?

And maybe it is the video resolution, but the fonts on Windows seem to be a little pixelated. Is that correct?

**Comment by swantzter** [comment] 2023-09-29 12:56
@ransome1 yes, that's what's happening with the theme.

The language selection is empty by default after an update, but I can expand it and doing so I see the expected options:
![image](https://github.com/ransome1/sleek/assets/10356719/985168ce-b6a1-4e6a-aa95-f752e00a615b)

The font is indeed a video resolution thing, if anything with the fonts the bold in +Project is a little fussy, and the contrast on C and below priority groups is a bit low in dark mode:
![image](https://github.com/ransome1/sleek/assets/10356719/37adec77-1fe7-43aa-a8bb-13992e843368)
![image](https://github.com/ransome1/sleek/assets/10356719/761ad3ed-5ee2-4a9b-92cb-79c48a11296f)

**Closed** 2023-10-09 20:28 UTC
Labels: bug

**Comment by ransome1** [comment] 2023-10-10 12:41
@swantzter could you please try to reproduce this in https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev15?

**Comment by ransome1** [comment] 2023-10-10 13:45
@swantzter that would be good. As for the contrast issue, I lowered the brightness of the background color by 20%, which will look like this:
<img width="54" alt="Bildschirmfoto 2023-10-10 um 3 44 11 PM" src="https://github.com/ransome1/sleek/assets/11188741/1c96f003-4bad-4c4a-b77c-840bcc69c103">

**Comment by swantzter** [comment] 2023-10-10 13:52
Yeah, I think that works better. Another would be to swap the text for C and below to some dark gray or black I guess

**Comment by swantzter** [comment] 2023-11-01 08:29
@ransome1 this might be because of the introduction of the store migration thing, but I've had this problem in 2.0.0 and 2.0.1 again

**Comment by ransome1** [comment] 2023-11-01 08:31
Hopefully for the last time. As mentioned in the release notes this needed to happen to onboard you to the migrations function of electron-store. Please let me know if this happens with the update to 2.0.2. It is not suppose to.
