### ISSUE TITLE
Document where `user-preferences.json` is

### ISSUE THREAD

**Issue by callegar** [ransome1/sleek#487] opened 2023-04-29 20:19 UTC
**Is it an actual bug?**

Probably so, since the file is mentioned in the wiki, but impossible to find.

**Did you check if the bug has already been reported?**

yes

**Describe the bug**

The wiki mentions a `user-preferences.json` file, but I do not appear to be able to find it.
Does it get autocreated on first usage of the software?

**To Reproduce**

Seek the `user-preferences.json` file.

**Do you see any error entries in sleeks developer tools?**

N/A

**Expected behavior**

I expect to be able to find the `user-preferences.json` file. Saying where it is accessed in the *About* screen or in the wiki would help. The wiki only documents the Mac case. Other bugs suggest that on linux it should be in `~/.config/sleek`, but I do not have that dir.

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04, Manjaro
 - Version of sleek 1.3.1
 - Source: Flathub

**Comment by callegar** [comment] 2023-04-29 20:30
OK, found the file in `~/.var/app/com.github.ransome1.sleek/config/sleek/user-preferences.json`. Makes sense now, but not obvious...

**Comment by ransome1** [comment] 2023-05-15 15:11
It's hard to document this, every OS and every distribution channel (Snap, Flat, AUR, Windows Standalone, Windows setup, Mac App Store, Brew on MacOS, Windows Store and so on) stores it in different locations. In sleek we use the default location of your user data, defined by the distribution channel.

This is why I stay vague on the documentation: `These preferences can be changed in user-preferences.json which is located in your user data folder. For example on a Mac this is in /home/$USER/Application Support/sleek`
https://github.com/ransome1/sleek/wiki/Hidden-preferences,-custom-variables-and-command-line-parameters

If you for instance use Flathub, it is Flathub, which decides where it stores user data. Not sleek. Please understand I simply can't document this for each and every distribution. 

As this is not a bug I would like to close this.

**Closed by ransome1** 2023-05-15 15:11 UTC
Labels: bug

**Comment by callegar** [comment] 2023-05-15 19:00
I understand. Given the variety of possible locations, I wonder if it could be possible to *dynamically* determine the location of the file and provide it in the *about* dialog.

**Comment by ransome1** [comment] 2023-05-15 19:51
@callegar that might be possible, let me see what can be done about that.
