### ISSUE TITLE
quickly changing priority

### ISSUE THREAD

**Issue by kareliot** [ransome1/sleek#27] opened 2021-01-21 15:49 UTC
It’s really great to have nice, sleek and actively developed todo.txt app!
Thanks for the great work!

The way I have been working with the todo.txt syntax is that I use the priority to stand for the time period in which a task needs to be done: (A) is today, (B) is tomorrow, (C) is this week, and (D) is next week
Because of that I often need to reassign priorities and I would be great if this would be made easier by the app (and I guess it would be useful for many other use cases as well).

It could either happen via simple up/down buttons  – just like qtodotxt2 does it – or via a dedicated priority picker button – just like simpletask for android does it. In both cases, it would also be great to be able to change the priority via the keyboard (either up down or by simply typing the desired priority (A, B, C, etc...)

Keep up the great work

**Comment by ransome1** [comment] 2021-01-21 18:48
Hi @kareliot . It's funny that it tooks so long before somebody was asking for that obviously useful feature ;)

I think as as starter we can achieve this by a simple dropdown box, which I will implement as a PoC in the next couple of days. 

Also I think this would be a good first use case for the drag and drop feature that @koppor suggested. Like that you could just drag and drop todos from one priority group to the other. So if I find some time or anybody would be willing to put in a PR, this can be step number 2.

**Comment by koppor** [comment] 2021-01-21 20:15
For reference: The issue for drag'n'drop is this one: https://github.com/ransome1/sleek/issues/18

**Comment by kareliot** [comment] 2021-01-21 22:34
A dropdown box and drag'n'drop sound both like great options to achieve that (ideally coupled with a keyboard shortcut)
Thanks for the quick response!
Unfortunately, I cannot help with the implementation, though. But I am happy to test ;)

**Comment by ransome1** [comment] 2021-01-22 21:06
@kareliot. Please check https://github.com/ransome1/sleek/releases/tag/v0.8.4-Alpha

I added a simple priority picker for testing purposes. I only added A to G and will add the rest of the alphabet later on. 

Also there is a specific keyboard shortcut combination to add priorities while you have the add/edit todo window opened. Press **Shift** and **Ctrl** and **any key of the alphabet** at the same time and sleek should add the priority to the todo. There is still a minor usability drawback though, I need to fix. It happens when there is a project or context at the end of the todo. If this is the case and you add the priority sleek will focus the input field and immediatelly open the suggestion box for projects or contexts. That's not a bug, but it's a little ugly on usability.

**Comment by kareliot** [comment] 2021-01-25 09:46
sorry, I only got around testing it now.
Looks great and works well. 
One minor thing I noticed is that since the priority picker list opens on top of the priority picker button (rather than below), I have to move to the top of my screen to change the priority since I am only using the top priorities (A-D). It would be easier if the list opens below the picker so that the most often used priorities are much closer to the mouse already or to simply limit the priorities to the first few letters of the alphabet since I doubt that many people would actually use more than 6 or 7 different ones (and if they do they could still change them "manually").

The keyboard shortcut works fine. It would be great, though, if you could add a possibility to delete any given priority via the keyboard as well. Shift+Ctrl+- would work well, I guess.

Thanks again!

**Comment by ransome1** [comment] 2021-01-25 12:27
@kareliot , that's interesting, because I never saw the list opening to the top. It is suppose to open to the bottom. I'm not even sure if I could manipulate it to open to the top, as this is a native browser function as far as I know.

So it doesn't look like this on your version of sleek?
![priority_picker](https://user-images.githubusercontent.com/11188741/105705742-e28dee80-5f10-11eb-8c72-5faa6832f30d.png)

I also added the Shift+Ctrl+Minus shortcut which will be added into the next release :)

**Comment by kareliot** [comment] 2021-01-25 15:28
Interesting. On my machine it looks like this:

![Bildschirmfoto von 2021-01-25 16-17-01](https://user-images.githubusercontent.com/35163804/105725537-5e943080-5f29-11eb-9179-3fe613d5e8a0.png)


But this is probably due to the standard opening position of a windowed application right at the centre of my screen. If I move the window up a bit, the list opens towards the bottom. To make this a useful permanent solution or workaround, sleek would need to remember its window size and position, however, which at the moment it does not do on my laptop.

**Comment by ransome1** [comment] 2021-01-25 15:56
I can reproduce it by positioning sleek close to the bottom of my screen, so that die select list has not enough space to spread to the bottom. Then it will instead open to the top. Imo there is nothing I can do about it.

If i'll find the time at some point I will replace the select list with a individual solution that doesn't need to be scrolled. Maybe a table with several rows and columns. That's on my roadmap now, but should not be part of this issue.

**Comment by ransome1** [comment] 2021-01-27 07:57
@kareliot , I'm closing the issue to clean up a little.

**Closed by ransome1** 2021-01-27 07:57 UTC
Labels: enhancement
