### ISSUE TITLE
Selection of multiple tasks

### ISSUE THREAD

**Issue by aubreyz** [ransome1/sleek#291] opened 2021-10-28 20:03 UTC
Needs a method to select multiple tasks, and to apply tag additions or removals, date changes and priority changes to all of those tasks (given that Sleek should be aiming to be the best todo.txt app, the various  feature requests I have added are pretty much essential (taking simpletask on android as the current gold standard)

**Comment by ransome1** [comment] 2021-11-05 09:14
@aubreyz this looks like a duplicate of https://github.com/ransome1/sleek/issues/56 and should be discussed there. As there is not a lot dev capacity at the moment, major feature requests are not being worked on. I focus my little time on bugfixes only. You can contribute to this project easily if you have knowledge in Javascript.

**Closed by ransome1** 2021-11-05 09:14 UTC
Labels: feature request

**Comment by aubreyz** [comment] 2021-11-05 09:16
OK, but this seems pretty fundamental

**Comment by ransome1** [comment] 2021-11-05 09:22
I generally agree, but at the moment I'm afraid I can't work on it ... at least yet.

**Comment by aubreyz** [comment] 2021-11-05 09:58
Fair enough - I know that issue tracker lists are not the place for meta-development comments but I'll do so anyway. 

It is unfortunate that there are a variety of todo.txt bits of software out there, all of which start off in a promising way, and then end up being abandoned. By far the most well developed well considered interface is simpletask - but only for android. That developer ended up walking away (mostly) from the project in a hissy fit after ludicrous changes made by google to allowable apps and the storage interface. 

The simple fact is that, as of now, this app (Sleek) looks to be the most promising line of development for a Windows App. It would seem a great pity if it ended with the same fate as all the rest. It can't really be a half job to be of use at all. I would use simpletask as the gold standard. 

It would mean having a decent filtering mechanism that can save filter and sorting options in sets, no non-standard messing around with the todo.txt file itself (no sorting for example), ability to work on multiple items, better handling of threshold dates. The fact is that you have a great basis for getting there (and to be the best of the bunch) so don't give up (in the long run). What developers tend to do when pressed for time is to suggest that users do development. This is good, but in practice projects that are not driven forward by a single predominant person very rarely succeed until they become mature enough to permit that.
