### ISSUE TITLE
More closely replicate keyboard shortcuts from todotxt.net

### ISSUE THREAD

**Issue by intrepidsilence** [ransome1/sleek#70] opened 2021-03-22 16:10 UTC
It may be beneficial to clone the keyboard shortcuts from todo.txt more closely (changing existing and adding some that are missing) if you want to capture the crowd that uses it to make transition more smooth.

Some of those features are very handy and moving away from it can be painful, especially when there is no equivalent shortcut.

**Comment by ransome1** [comment] 2021-03-22 18:09
Hi @intrepidsilence , I don't know the shortcuts of the todo.txt app you're mentioning. I'm not even sure which one you're referring to as there a zillions out there.

But if you provide a detailed information on the shortcuts I can check what makes sense in sleek.

**Comment by intrepidsilence** [comment] 2021-03-22 19:54
Sorry, I should have specified.  It is probably the most likely client for Windows users to be using (guessing here). http://benrhughes.github.io/todotxt.net/

You can see the list of keyboard shortcuts here:
https://github.com/benrhughes/todotxt.net

Thanks for considering it!

**Comment by shulist** [comment] 2021-03-23 00:28
@ransome1 I've put a list of the referenced Keyboard Shortcuts in KeyBoardShortcuts_Proposed.md

**Comment by arthurmarquesv** [comment] 2021-04-06 12:24
This would be a plus for me too! It would be beneficial to use the keyboard not only for editing, deleting, filtering etc., but to navigate between tasks too. In Todotxt.net I can even select multiple tasks using simple *text-editor-like* shortcuts (like control + arrow) when I want to copy those in my bullet journal (using control + C). 

The absence of a more keyboard-friendly environment is the only thing blocking my transition from Todotxt.net to Sleek.

**Comment by intrepidsilence** [comment] 2021-05-14 19:27
@ransome1 Thanks very much for this. I tested and the shortcuts that do not require a modifier work fine. The ones that should be using CMD are only responding with CTRL as if it was Windows.

**Comment by shulist** [comment] 2021-05-18 16:18
@ransome1
>  
>Where can I find KeyBoardShortcuts_Proposed.md and does it differ from https://github.com/benrhughes/todotxt.net?
>
I copied that from the bottom of the [Ben Hughes ToDoTxt.net ReadMe.MD](https://github.com/benrhughes/todotxt.net/blob/dev/README.md). Therefore it is identical.

**Comment by ransome1** [comment] 2021-05-26 18:32
@intrepidsilence, I looked into it and learned that the CMD key does only work in JavaScript if it is called for in a certain way. And by accident I am calling it only for the priority change in this particular way. 

Could you please double check if the CMD + O **is not** working and the CMD + Alt + Up (in the Add/Edit window) for changing the due date **is actually** working? If this is the case the issue is resolved easily.

I stumpled upon a possible issue with the todotxt.net shortcuts on MacOS. To remove a priority the shortcut is suppose to be Alt + Arrow Rigt or Arrow left. As far as I remember from my old Mac days, Alt + arrow keys is usually been used to jump from word to word right? Which is something quite important imo. Can you also confirm that Alt + Arrow right/left is removing a given priority on a todo?

@shulist , yep you're right. Some shortcuts just can't be applied, as sleek has been designed differently than todotxt.net. But some (changing threshold, or toggle completion) will be enhanced further on. This is the state of progress on the shortcuts so far:
![image](https://user-images.githubusercontent.com/11188741/119712759-3974e780-be61-11eb-941b-5991d5943af2.png)

**Comment by ransome1** [comment] 2021-05-27 07:42
I'm closing here, so clean up the issue list. As for now this is all shortcuts I am able to borrow from todotxt.net. All further features will be harmonised with todotxt.net. 

If anybody is experiencing any issues with the shortcuts implemented so far, please report back here and I'll reopen.

**Closed by ransome1** 2021-05-27 07:42 UTC
Labels: enhancement, feature request

**Comment by intrepidsilence** [comment] 2021-05-27 17:42
@ransome1 Ok, so CMD+O does nothing. CMD+ALT+Up/Down work fine as does ALT+Left/Right.

**Comment by ransome1** [comment] 2021-05-27 17:47
@intrepidsilence, this should be fixed in https://github.com/ransome1/sleek/releases/tag/v1.0.5-1. I hope it works for you.

**Comment by intrepidsilence** [comment] 2021-05-27 17:53
CMD+O is now functional.  Thanks!

**Comment by intrepidsilence** [comment] 2021-05-27 18:35
Also, I want to say thank you for taking this one on and delivering.  I am very grateful and I hope this helps increase this tool's ability to be picked up by a wider audience.
