### ISSUE TITLE
Feature request: Add method to setting threshold date from data entry form

### ISSUE THREAD

**Issue by aubreyz** [ransome1/sleek#289] opened 2021-10-28 19:41 UTC
Little more to be said than the title. If sleek uses threshold dates (which it does and should do) suggest make an easy way to enter those (in parallel with due dates which I don't use at all in fact)!

**Comment by dlaidig** [comment] 2021-10-29 22:33
This looks like a duplicate of #234, right?

**Closed as not planned** 2023-08-07 18:51 UTC
Labels: feature request
