### ISSUE TITLE
plus signs are incorrectly interpreted as project references (only in drawer)

### ISSUE THREAD

**Issue by andrei-a-papou** [ransome1/sleek#649] opened 2024-01-26 09:10 UTC
## Steps to reproduce
1. Hit `Ctrl+N` to open the new todo dialog
2. type _A+B = C +test_project_ and save the todo

## Actual result
In the drawer, the _+B_ part is interpreted as a non-existent _B_ project

## Expected result
The _+B_ part should be treated as part of the todo text

## Attached GIF

![sleek_bug_plus_sign_parsing](https://github.com/ransome1/sleek/assets/30468319/090bac9e-1f58-4cc8-954c-c4211d94c8e2)

**Comment by ransome1** [comment] 2024-01-26 09:16
Hey @andrei-a-papou . Although the gifs are of course very helpful, can I kindly ask you to use the issue-templates? It really help keeping this backlog tidy and I would like to avoid that other users see issues without the template and also start creating those like this.

If the templates don't make sense to you, please let me know how they should be re-structured and I will take care of it. Thanks a lot :)

**Comment by andrei-a-papou** [comment] 2024-01-26 10:02
@ransome1 I think the templates are a bit verbose but this is totally fine if one can trim them down to only keep the necessary information when reporting a bug. I agree templates are helpful in many ways, of course. 

I've corrected the bug report above, is this good enough? Would you add more info to it, if yes, could you give me an example of what's missing?

**Comment by ransome1** [comment] 2024-01-26 10:09
@andrei-a-papou its perfect like that. This is so much.

**Comment by ransome1** [comment] 2024-01-26 18:55
@andrei-a-papou this could be a duplicate of https://github.com/ransome1/sleek/issues/617.

**Comment by andrei-a-papou** [comment] 2024-01-26 20:56
@ransome1 It looks that way, yes. I missed that other bug report.

**Comment by ransome1** [comment] 2024-01-26 21:22
<img width="376" alt="Screenshot 2024-01-26 at 10 19 35 PM" src="https://github.com/ransome1/sleek/assets/11188741/9fd2eaf6-d5c8-4bc1-9f49-425ac52edb90">

Is this really what it looks like on your system? Definitely something wrong with the formatting here. This is some Linux distro you're using, right?

**Comment by andrei-a-papou** [comment] 2024-01-26 22:22
This is a Debian box, yes. What exactly do you mean by wrong formatting? I noticed recently that little numbers inside circles are no longer centered properly, I don't think sleek had this issue before.

**Comment by ransome1** [comment] 2024-01-26 22:27
This is how it looks like on my Ubuntu VM
<img width="360" alt="Screenshot 2024-01-26 at 11 23 40 PM" src="https://github.com/ransome1/sleek/assets/11188741/4767b7b3-80f2-4fba-bef3-3a5688c799fe">

And this is how on my macOS
<img width="342" alt="Screenshot 2024-01-26 at 11 25 46 PM" src="https://github.com/ransome1/sleek/assets/11188741/cfa51b7c-667e-42e2-8760-d816f9c4a259">

Are you on v2.0.8?

**Comment by ransome1** [comment] 2024-01-27 09:20
> @ransome1 It looks that way, yes. I missed that other bug report.

Closing here, will be handled in https://github.com/ransome1/sleek/issues/617

**Closed by ransome1** 2024-01-27 09:20 UTC
Labels: bug

**Comment by andrei-a-papou** [comment] 2024-01-27 11:38
Yes, this is v.2.0.8, AppImage. On Ubuntu, do you use AppImage or native package format?

**Comment by andrei-a-papou** [comment] 2024-01-27 11:39
The screenshot you took was from a GIF, which had been downsampled by the screencasting app. Here's a normal PNG image:
![image](https://github.com/ransome1/sleek/assets/30468319/f776cc6e-658d-48a9-9eeb-e7cf7af8df39)
