### ISSUE TITLE
Since last update (2.0.12), completing a task causes ToDo.txt file to be "lost"

### ISSUE THREAD

**Issue by TriggerDingus** [ransome1/sleek#694] opened 2024-03-27 16:11 UTC
### Important ###
Please follow this template strictly when reporting bugs. 

Reports that do not adhere to this template will not be addressed and will be closed.

App Ver: 2.0.12

OS:   Both:  Linux LMDE 6,  Pop!_OS 22.04

Package:  Flatpak

Expected:  After completing an item, ToDo list to be displayed as usual.

Actual:   The app apparently thinks ToDo list is still open, but all To Do items are removed from display. 

To recreate:    Open  a ToDo list. Complete an item by clicking the checkbox on the left of the item, when the entire ToDo list is cleared from the display and what is shown is "No ToDos in this file".
The work-around is to close the app and re-open it, where all items are then displayed again. The item that was selected for completion is being completed, so the issue is apparently occurring upon refresh of the list.

**Screenshots:**
See attached - this is what  I see after completing a ToDo item. There are literally hundreds of ToDo items in the file, though.

![cap](https://github.com/ransome1/sleek/assets/75340371/fc88f176-ad41-4cac-8299-e3ac8b3a1ea2)

**Comment by ransome1** [comment] 2024-03-27 16:24
@TriggerDingus does this just happen when you finish a task or also, when you create or delete a task?

Is there a file sync running in your environemnt? Syncthing, Dropbox, Google or something similar?

**Comment by ransome1** [comment] 2024-03-27 16:45
@TriggerDingus also, is this a duplicate of https://github.com/ransome1/sleek/issues/692?

**Comment by TriggerDingus** [comment] 2024-03-27 16:46
> @TriggerDingus does this just happen when you finish a task or also, when you create or delete a task?
> 
> Is there a file sync running in your environemnt? Syncthing, Dropbox, Google or something similar?

I know this answer is gonna suck, but it's only upon Completion and it seems to be only for a large percentage of tasks I complete  - maybe 75% of them since the last app update.  I don't yet recognize any particular consistent features of the tasks I'm completing that might trigger this issue, unfortunately. It is happening on two completely different systems of mine, though.  (I sync the same file between them using Syncthing)

**Comment by TriggerDingus** [comment] 2024-03-27 16:47
> @TriggerDingus also, is this a duplicate of #692?

Yes, it actually is. I did a search for the issue assuming others were experiencing it as well but apparently I didn't use the right search terms.

**Comment by ransome1** [comment] 2024-03-27 16:49
Then let me suggest we handle it over at https://github.com/ransome1/sleek/issues/692. Closing here.

**Closed by ransome1** 2024-03-27 16:49 UTC
Labels: bug
