### ISSUE TITLE
Timeout error when slow to select todo.txt file

### ISSUE THREAD

**Issue by repent** [ransome1/sleek#219] opened 2021-07-19 12:46 UTC
When the user is very slow to select a todo.txt file when running the app for the first time, a timeout error occurs.

I opened the app for the first time, chose to use an existing todo.txt file, and was very slow to make a selection.  This error occurred (repeatedly):

![image](https://user-images.githubusercontent.com/8235522/126161438-545cccdf-b2b8-468b-ac99-b82cd9b05774.png)

I expected it just to wait patiently for me to select a file.

No errors in the console.

Sleek 1.0.9 on Windows 10 downloaded from the Windows store.

**Comment by ransome1** [comment] 2021-07-19 14:14
Hi @repent sounds oddly interesting ;)

I freshly installed the version from Windows Store as well as the portable one here on Github. On both I started up seeing the onbaording, clicked the "Open todo.txt" button and waited up to 10 minutes each. Nothing really happened. 

Can you please check if you're experiencing the same issue with the portable non-store version https://github.com/ransome1/sleek/releases/download/v1.0.9/sleek-1.0.9-win.zip

**Comment by ransome1** [comment] 2021-07-20 05:53
@repent I think I found the cause. It must have been at least 10 minutes you waited, correct?

It should be fixed in the 1.1.0 release. Thanks for reporting it.

**Comment by repent** [comment] 2021-07-27 09:48
@ransome1 Yes it probably was that long.  After I opened the window, I realised I had to go and move my todo file over from another machine.

**Comment by ransome1** [comment] 2021-07-27 09:50
But it shouldn't have happened anyway ;)

The 1.1.0 has just been pushed to the Windows Store. It includes a fix for it and should be available tomorrow.

**Comment by donludovico** [comment] 2021-08-05 12:34
Hi, I have a similar thing with 1.1.0 on Win 10 (from Windows Store as well as downloaded Setup.exe): I run Sleek (e.g. minimized to notification bar) and do *not* open any file. After approx. 10 min I get the following error message:
![grafik](https://user-images.githubusercontent.com/10374564/128350612-ca852837-c77b-4323-901a-98dd89241de7.png)

Could you please have a second look at that issue?

Thanks a lot!

**Comment by ransome1** [comment] 2021-10-03 07:54
@repent Does this still happen in https://github.com/ransome1/sleek/releases/tag/v1.1.2-rc.4 on your side?

**Comment by ransome1** [comment] 2021-11-07 06:41
I assume this is fixed since https://github.com/ransome1/sleek/releases/tag/v1.1.2. If not, please feel free to report back here.

**Closed by ransome1** 2021-11-07 06:41 UTC
Labels: bug
