### ISSUE TITLE
Square instead of text in file dialog

### ISSUE THREAD

**Issue by NoeTerrier** [ransome1/sleek#424] opened 2022-10-15 12:07 UTC
When trying to open or create a file, the file dialog show text as squares instead of letters. 

I'm on Ubuntu 22.04.1 LTS running version 1.2.6 of Sleek from snap.

![Capture d’écran du 2022-10-15 13-49-48](https://user-images.githubusercontent.com/56764430/195985431-5f1b8418-5222-4742-a60a-08833e7b50da.png)

I tried this fix for a similar issue with chromium and gnome-calculator: https://askubuntu.com/questions/1224125/font-characters-displayed-as-squares-in-ubuntu-18-04
But it doesn't changed anything. Then I'm not sure if the issue is related to Sleek or ubuntu, but I prefer to inform you in case you can change anything.

**Comment by ransome1** [comment] 2022-10-16 09:43
@NoeTerrier thanks for reporting this. The issue is not new. In fact the second issue (https://github.com/ransome1/sleek/issues/2) ever on Github was about this weird behavior. We never actively solve it, it just came and went. So I assume it is either something within Linux distributions or a module of Electron. 

Are you installing sleek using Snap's command line? You could try downgrading and see if it still happens, maybe this helps us narrowing it down. For instance to version 1.2.2:
`sudo snap refresh sleek --channel=1.2.2/stable`

**Comment by ransome1** [comment] 2022-11-09 08:07
@NoeTerrier does this still happen in 1.2.8, which is the current release on Snap?

**Comment by NoeTerrier** [comment] 2022-11-11 09:48
@ransome1  With version 1.2.9 snap cannot launch sleek:

`~$ sleek 
/snap/sleek/1100/snap/command-chain/desktop-launch: line 602: /snap/sleek/1100/sleek/sleek: Permission denied
/snap/sleek/1100/snap/command-chain/desktop-launch: line 602: exec: /snap/sleek/1100/sleek/sleek: cannot execute: Permission denied
`

**Comment by ransome1** [comment] 2022-11-11 21:18
@NoeTerrier yes there another bug report on this. So far I haven't found a fix for this, so I downgraded the latest sleek version on Snap to 1.2.8 again. I really wonder how you could get the 1.2.9 version. Did you install it from the Edge channel on Snap?

**Comment by ransome1** [comment] 2022-11-30 10:09
> @NoeTerrier does this still happen in 1.2.8, which is the current release on Snap?

@NoeTerrier Have you checked the 1.2.8 (currently on Snap) and can you confirm this issue still occurs? If not, it would be great, if you could close this issue. Thanks a lot.

**Comment by ransome1** [comment] 2022-12-08 07:39
Due to no response, I am closing here. Feel free to reopen if this issue persists.

**Closed by ransome1** 2022-12-08 07:39 UTC
Labels: bug
