### ISSUE TITLE
Some content not visible / hidden when there's no scrollbar (everything in category C and without category)

### ISSUE THREAD

**Issue by thekryz** [ransome1/sleek#655] opened 2024-02-05 10:24 UTC
**App Version:** 2.0.8
**Platform:** macOS Sonoma 14.2.1, MacBook Air 2020 (Intel)

**Installation Method:** Direct Download

**Expected Behavior:**
Show all open TODOs (when no filters applied)

**Actual Behavior:**
Shows all TODOs in categories A and B, but only header for C - and no TODOs with no priorities assigned. This changes only when the window is reduced to force a scroll bar to appear.

Some context: My setup has my MacBook Air in the middle, a 1080p screen on the left and a 2560*1440 screen on the right:
<img width="391" alt="Bildschirmfoto 2024-02-05 um 11 19 15" src="https://github.com/ransome1/sleek/assets/10432441/fabd17a6-284c-4342-bbf5-af7c351c7caa">

I want to keep sleek on the right screen, and maximized to list as many TODOs as possible.

**Steps to Reproduce:**
1. Open the app.
2. Maximize sleek on my vertical external screen
3. (sometimes) Push a button (such as the filter button on the upper left side) to make the scrollbar disappear
4. Observe the unexpected behavior.

**Screenshots:**

Problem when no scrollbar is visible (everything under the yellow "C" is hidden!)
![Bildschirmfoto 2024-02-05 um 11 14 51](https://github.com/ransome1/sleek/assets/10432441/94ff5300-e69a-46e9-afba-ba5bf0e36f8a)

No problem when the window is smaller, forcing a scrollbar to appear - and then scrolling down:
![Bildschirmfoto 2024-02-05 um 11 15 02](https://github.com/ransome1/sleek/assets/10432441/cb7f50c1-cd18-4d99-92a0-1c48b8617bc7)

**Comment by ransome1** [comment] 2024-02-08 20:32
@thekryz thank you for this exemplary bug report!

Can I ask you to check, if this might be a duplicate of this report? https://github.com/ransome1/sleek/issues/639

**Comment by thekryz** [comment] 2024-02-08 20:50
> @thekryz thank you for this exemplary bug report!
> 
> Can I ask you to check, if this might be a duplicate of this report? #639

Yes, it looks like they describe the same issue.

**Comment by ransome1** [comment] 2024-02-09 11:09
Duplicate of https://github.com/ransome1/sleek/issues/639. Will be dealt with over at 639.

**Closed by ransome1** 2024-02-09 11:09 UTC
Labels: bug
