### ISSUE TITLE
It does not remember dark theme on Linux

### ISSUE THREAD

**Issue by gerroon** [ransome1/sleek#552] opened 2023-10-21 02:55 UTC
## Bug Report

**App Version:** [Enter app version here]
2.0.0.dev17

**Platform:** [Windows / macOS / Linux]
Debian 

**Installation Method:** [App Store / Direct Download / Other]
.deb

**Bug Description:**
It does not remember the dark theme

**Steps to Reproduce:**
pref->dark theme->quit->open sleek->light theme

**Expected Behavior:**
it should always set to dark theme

**Actual Behavior:**
sets to light theme

**System Information:**
- OS Version: Debian testing x64, Cinnamon desktop
- Processor: Intel Core i5
- RAM:  8GB
- Graphics Card: Intel
**Reproducibility:**
- [Always / Sometimes / Rarely / Unable to Reproduce]

**Comment by ransome1** [comment] 2023-10-21 10:24
@gerroon I can't reproduce this on Arch Linux and on Ubuntu using the AppImage. Unfortunately I can't test the .deb since my architecture (arm64) won't let me install nor build it.

Can you start the Debian build using your terminal and if so do you see any errors popping up?

Also if you switch to dark or light theme, does this change the `colorTheme` value in your [your config file](https://github.com/ransome1/sleek/wiki/User-data-folder-location)?

**Comment by ransome1** [comment] 2023-10-21 10:25
And also: if you're using the .deb release, does sleek has an app icon in your app bar / dock?

**Comment by gerroon** [comment] 2023-10-21 16:47
the `colortheme` in the config below is set to `dark` it still opens the light theme.
 
```config.ts: sleek userdata is located at: /home/USER/.config/sleek/userData2.0.0-dev17                                                            
config.ts: Tray created                                                                                                                            
main.ts: Main window has been created successfully                                                                                                 
main.ts: Menu created                                                                                                                              
main.ts: Tray created                                                                                                                              
config.ts: Tray created                                                                                                                            
config.ts: Tray created                                                                                                                            
config.ts: Tray created                                                                                                                            
Styles injected found in CSS file: /home/USER/.config/sleek/userData2.0.0-dev17/customStyles.css                                                 
MESA-INTEL: warning: Haswell Vulkan support is incomplete                                                                                          
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed                                                                            
ipcEvents.ts: Received config value for language                                                         
```

**Comment by Bleskocvok** [comment] 2023-10-26 16:01
Perhaps somewhat related: the button `View` -> `Toggle theme` doesn't work **at first** (neither does the associated shortcut `Alt+Ctrl+D`).

However, if I go to settings and change the theme from there, both the button and shortcut start working to toggle the theme as expected (until `sleek` is closed).

(Version is: `2.0.0.dev17`)

**Comment by gerroon** [comment] 2023-10-26 16:39
(until sleek is closed).  I have the same experience.

**Comment by ransome1** [comment] 2023-10-27 15:26
> Perhaps somewhat related: the button `View` -> `Toggle theme` doesn't work **at first** (neither does the associated shortcut `Alt+Ctrl+D`).
> 
> However, if I go to settings and change the theme from there, both the button and shortcut start working to toggle the theme as expected (until `sleek` is closed).
> 
> (Version is: `2.0.0.dev17`)

Are you on Linux (Cinnamon?) as well?

**Comment by ransome1** [comment] 2023-10-27 15:28
@gerroon @Bleskocvok also, can you provide me with some feedback, if you're also affected by this on Cinnamon? https://github.com/ransome1/sleek/issues/550

**Comment by Bleskocvok** [comment] 2023-10-28 15:19
> Are you on Linux (Cinnamon?) as well?

I am on Xubuntu (using XFCE as my desktop environment). 

Ad https://github.com/ransome1/sleek/issues/550: I used to be affected, but yesterday's `2.0.0-dev19` fixed the icon for me.

The issue with dark theme not being remembered and the `Toggle theme` button issue still persist in `2.0.0-dev19`.
Both using `.AppImage` and `.deb` installation methods yield the same behaviour for me.

(I also tried `sleek 2.0.0-dev19` on Windows 10 and the dark theme works perfectly fine there, if that's helpful.)

If I run `sleek` from the command line, it outputs similar errors to what @gerroon sent above:
```
$ sleek
config.ts: sleek userdata is located at: /home/USER/.config/sleek/userData2.0.0-dev19
config.ts: Tray not shown
main.ts: Main window has been created successfully
main.ts: Menu created
main.ts: Tray not shown
config.ts: Tray not shown
config.ts: Tray not shown
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[8678:1028/170936.513739:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
config.ts: Tray not shown
Styles injected found in CSS file: /home/USER/.config/sleek/userData2.0.0-dev19/customStyles.css
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[8723:1028/170936.647900:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[8697:1028/170936.710193:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
ipcEvents.ts: Set sorting to [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
ipcEvents.ts: Set isDrawerOpen to false
ipcEvents.ts: Set isSearchOpen to false
ipcEvents.ts: Set zoom to 100
```

**Comment by ransome1** [comment] 2023-10-28 16:37
I think I have just been able to reproduce this. Thanks for reporting it.

A fix will be part of the next release.

**Closed** 2023-10-28 16:44 UTC
Labels: bug
