### ISSUE TITLE
When sorted primarily by due-date, incorrect date labeled as "Today"

### ISSUE THREAD

**Issue by gentlecolts** [ransome1/sleek#352] opened 2022-03-27 22:28 UTC
**Is it an actual bug?**
Yes

**Did you check if the bug has already been reported?**
Did not see anything that looked like this

**Describe the bug**
When sorted primarily by "Due", the date labeled as "Today" is incorrect, and tomorrow is currently being labeled as such.  This does not appear to be affecting the desktop notifications, and does not affect the mouse-over text on the clock icons, only affecting the date itself shown above each day's due items. 

**To Reproduce**
1. Go to Settings
2. Set "Sort by" to primarily sort by "Due"
3. Observer incorrect labels

**Do you see any error entries in sleeks developer tools?**
No

**Expected behavior**
Correct labels

**Screenshots**
![image](https://user-images.githubusercontent.com/2545023/160303707-6d8b233f-417e-4c10-8885-f6db52a79b1a.png)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Version of sleek: 1.1.7
 - Source: Arch User Repository

**Comment by ransome1** [comment] 2022-03-28 05:53
@gentlecolts interesting. I can't reproduce it locally but that doesnt have to mean anything. Can I ask in which timezone you're Manjaro is setup?

**Comment by ransome1** [comment] 2022-03-30 09:54
@gentlecolts I looked further into it but am still not able to reproduce this :( I installed a free Manjaro vm and set its timezone to New York but it works fine on my side (which doesn't have to mean anything)

Can I ask you to install the AppImage of this latest release and tell me if there is any change? https://github.com/ransome1/sleek/releases/tag/v1.1.8-rc.2

**Comment by gentlecolts** [comment] 2022-03-30 15:36
Well whatever's going on has persisted through rebooting.  Definitely strange, if this isn't super easy to reproduce then I can only assume something weird on my end is happening, but I can't begin to imagine what might cause this discrepancy if not sleek itself.  Running the Appimage produces the same result for me as well.

**Comment by Feardt** [comment] 2022-03-30 16:18
I've had the same problem over the past couple of days. Items showing as due "today" (3/30/22) have due dates of tomorrow (3/31/22). I'm in the US, timezone/date is correct in Plasma time/date settings, I'm on ArcoLinux/KDE Plasma. I've tested the stable AUR/Flatpak packages and also the v1.1.8-rc.2 appimage. All have the same bug for me as well.

**Comment by ransome1** [comment] 2022-04-04 10:44
@gentlecolts @Feardt I was able to reproduce it and I think it is fixed now. Can you guys check if this still happens on your side in https://github.com/ransome1/sleek/releases/tag/v1.1.8-rc.3

**Comment by gentlecolts** [comment] 2022-04-04 14:13
It looks like that did it for me, thanks!

**Comment by Feardt** [comment] 2022-04-05 20:45
Worked for me too- thank you for fixing this!

**Closed** 2022-04-07 14:27 UTC
Labels: bug
