### ISSUE TITLE
Do not reorder entities

### ISSUE THREAD

**Issue by intrepidsilence** [ransome1/sleek#92] opened 2021-04-08 13:04 UTC
It would be better to leave tags and contexts where they are written in the text. This way they can be part of a sentence without duplicating efforts.

Rather than moving Tags and Contexts, etc to the end of the line just leave them where they were added and add the formatting to them in place. This allows them to be part of a sentence that flows but they can still be found easily. This will reduce the need to repeat works in the task and in the tag/context/etc.

**Comment by ransome1** [comment] 2021-04-08 13:33
Hello @intrepidsilence, this is a duplicate of https://github.com/ransome1/sleek/issues/68

**Closed by ransome1** 2021-04-08 13:33 UTC

**Comment by intrepidsilence** [comment] 2021-04-08 13:53
Oops, sorry! Githubbing before coffee is always a bad idea.
