### ISSUE TITLE
Search box loses focus after typing each character

### ISSUE THREAD

**Issue by velardevines** [ransome1/sleek#80] opened 2021-03-24 17:28 UTC
**Describe the bug**
Search box loses focus after typing a single character. 

**To Reproduce**
1. Ctrl-F to position cursor in Search box
2. Type anything. Focus is lost after first character. 
3. Ctrl-F to position cursor in Search box
4. Type anything. Focus is again lost after first character. 

**Expected behavior**
To type search term in Search box

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Linux (Beta) on Chromebook with Chrome OS v90.0.4430.30
 - Browser: Chrome & Firefox 
 - Version of Sleek 0.9.7 

**Additional context**
None

**Comment by velardevines** [comment] 2021-03-24 17:37
Yes, you are correct. Problem occurs when the filter side bar is open.  

Earlier versions did not contain this error; at least on my install.

**Comment by ransome1** [comment] 2021-03-24 17:41
I improved three things and broke one, classic ;)

It's being fixed in the next release. Thanks for bringing it up! 

By the way, did the latest Snap release work for you?

**Comment by velardevines** [comment] 2021-03-24 17:47
No, after installing 0.9.7 using Snap, I received the following error when executing Sleek. I posted a screenshot on the Snap Forum but here is the error:

$ sleek
No protocol specified
The futex facility returned an unexpected error code. Aborted (core dumped) 

Thanks for working so diligently on Sleek. I use it every day on an Intel based Chromebook laptop. I don't really need Sleek to run on ARM but if it did then I could use Syncthing and have my tasks available on the Chromebook tablet as well as the Chromebook laptop.

**Comment by ransome1** [comment] 2021-03-24 17:50
Good to hear you're using Syncthing. It's just great and a great solution also for keeping todo.txt files sync. It even works flawlessly on Android phones where you can use SimpleTask as a perfect todo companion app.

Anyway, I will try to figure out what is going wrong with the Snap version on ARM devices.

**Comment by velardevines** [comment] 2021-03-24 17:56
I agree and have tried SimpleTask on my phone. I'm having a problem with not being able to specify the directory location of the Sleek files on the phone in SimpleTask.  It's odd though because SimpleTask on the ARM machine works great and I open todo.txt files using SimpleTask ... at least until Sleek works on the ARM machine  ;)

**Comment by ransome1** [comment] 2021-03-24 18:02
If you're having problems with finding the todo.txt file with Simpletask it is caused by some Android permission issues. There is a release where this issue has been worked around and it works well on my phone. You can find a link to an apk here: https://github.com/mpcjanssen/simpletask-android/issues/1100

**Comment by velardevines** [comment] 2021-03-24 18:09
Yes, that's exactly the  problem I have with SimpleTask on my phone.  Thanks very much for the link. Will be nice to have the todo.txt files working on the phone.

**Comment by ransome1** [comment] 2021-03-24 18:28
By the way, I just learned that Flatpaks by default are being built for all kinds of architectures, including ARM. And as sleek is available on Flathub too, you might give it a try if you have some free time for it: https://www.flathub.org/apps/details/com.github.ransome1.sleek

**Comment by ransome1** [comment] 2021-03-27 20:29
Released as part of https://github.com/ransome1/sleek/releases/tag/v0.9.8

**Closed by ransome1** 2021-03-27 20:29 UTC
Labels: bug
