### ISSUE TITLE
2 little issues in 0.9.0

### ISSUE THREAD

**Issue by arthurmarquesv** [ransome1/sleek#41] opened 2021-02-09 16:58 UTC
Hi!
When I open the last build, I encountered 2 little issues:

1. Sleek don't show my tasks until I search for "all" on the search bar;
2. The "error and event logging" window don't close even after the activation of the related option.

![skeek-issues-01](https://user-images.githubusercontent.com/78812600/107398195-2589bd80-6ade-11eb-9ca4-3a2d8e3cb279.jpg)
![Untitled-1](https://user-images.githubusercontent.com/78812600/107398228-2d496200-6ade-11eb-981b-d173bcea3176.jpg)

_Left: 0.9.0 build. Right: Microsoft Store's available build_

These behaviour occur both when I using _.txt_ or _.md_ extensions for the _todo_ file

I on the Windows 10 Pro 1909.

**Comment by ransome1** [comment] 2021-02-09 18:22
Hey @arthurmarquesv . Really helpful feedback, thanks!

Problem number 2 is solved, but with number 2 I'm having difficulties to reproduce it as my Windows (running in a VM) is not my friend right now.

Can I ask you to take a look into sleek developer console's output? In your upper menu (I don't know what it's called in Windows) select "About" and then "Developer Tools". The tools will open and you would need to select the "Console" tab. Then just reload sleek , so it gives you the blank page. Will there be any error entries in the developer console?

**Comment by ransome1** [comment] 2021-02-09 21:31
@arthurmarquesv. I added some bugfixes in this next alpha release: https://github.com/ransome1/sleek/releases/tag/v0.9.0-Alpha-3

I can't say if the issue you described has been fixed, as I couldn't reproduce it yet. But if you find some time, please feel free to give Alpha-3 a quick chance.

**Comment by velardevines** [comment] 2021-02-10 04:35
With Alpha 3 the Error and Event Logging window does close. 

@ransome1 : Regarding error 1 mentioned by @arthurmarquesv, it does not occur with Alpha 3.  All the tasks show when Sleek opens.  And there are no errors showing in the developer console when Sleek opens. 

Running Sleek on a Chromebook with Linux Crostini. 

--Bill

**Comment by arthurmarquesv** [comment] 2021-02-10 22:50
Just confirming what @velardevines reported: with Alpha 3 I can close the Error and Event Logging window and all my tasks are visible and organized when I open the app! Everything is working fine.

@ransome1 I couldn't find a way to see the apps's developer tools. I'm not tech savvy, so I don't understand if the steps you gave me  needed to be followed inside the app or in the OS. I tried to find the answer, but failed miserably 😅. Hope that what velardevines says is sufficient for now.

Thank you for the developing this beautiful application!

**Comment by ransome1** [comment] 2021-02-10 22:58
That's good to hear and I'm glad you like it. 

If it's fine with you, I'm going to close this issue. If you experience any other problems, feel free to open up another issue.

**Closed by ransome1** 2021-02-10 22:58 UTC
Labels: bug
