### ISSUE TITLE
Filter Issue when tasks beginn with letter t

### ISSUE THREAD

**Issue by Saturo78** [ransome1/sleek#311] opened 2021-12-21 09:53 UTC
to reproduce:
add Task "Test"
type "test ..." in the filter line
->found nothing
type "Test" in the filter line
->found "Test ..."

In the actual version search strings with t have to be written with capital letter T.
Maybe recognizing t as filter expression t:?

**Comment by ransome1** [comment] 2021-12-22 07:13
@Saturo78 thanks for reporting this, I'll look into it.

**Comment by zerodat** [comment] 2021-12-22 19:44
@Saturo78, thanks, I can reproduce this in v1.1.5.  As you suspected, this is a somewhat-unfortunate consequence of the filter language design.  Typing in the search box by default tries to use advanced search expressions if they are valid, and drops back to plain-text search if not.  Since "t" is a valid query meaning "give me all the tasks with a threshold date", it doesn't do a plain text match for the letter t.  Not so much a bug as a design choice.  Going forward, we could:

1. Leave it as is, and use `"t` to do the plain-text match for letter t.  The quoted string will always give you a literal or plain-text search on the contents of the string, and the closing quote can be omitted for brevity.
2. Have a way to select plain-text search versus advanced search, which is what I originally had in mind.  My suggestion was to begin the query with a "?" to indicate advanced search, and anything else would just be a plain-text match.
3. Require a colon after the keyword, so for instance `t:` would match tasks with a threshold date and `due:` would match tasks with a due date.  That might introduce some issues in the parsing grammar, but I think it might work.  If there is general support for that approach, I can give it a try.
4. I wouldn't recommend this, but I guess we could change the keyword for a threshold date from `t` to something longer like `threshold` since the single letter is particularly prone to confusion.

Let me know what you think.

**Comment by ransome1** [comment] 2021-12-22 20:43
Thanks for looking into it @zerodat

**Comment by zerodat** [comment] 2021-12-22 23:09
I tested this change in my version and it seems to work.  The syntax becomes a little ugly for date comparisons though.  Here are a couple of examples:
```
due: < tomorrow+1d
t: >= 2021-12-15
```
and so on.  This will be incompatible with previous versions, so people who are used to typing queries like `t >= 2021-12-15` will need to change to include the colon.

**Comment by Saturo78** [comment] 2021-12-23 07:56
In my humble opinion i would prefer using option 2 with "?" to distinguish between plain text search and filter query.

**Comment by ransome1** [comment] 2022-03-30 09:56
@zerodat @Saturo78 I'm a little off on this issue here. Can you guys tell me if this is still relevant?

**Comment by aubreyz** [comment] 2022-04-11 12:31
This problem is still there. No filters starting with t work

**Comment by zerodat** [comment] 2022-04-11 15:51
Hi, sorry that this ball was dropped.  Here's the explanation: If you look back in the thread to my post from Dec 22, there are a couple of options that were preferred.  @ransome1 you preferred option 3 (adding the colon) and @Saturo78 preferred option 2 (which is really what I prefer as well because it solves a variety of problems).  I have implemented both of these and I can send you a pull request once I know which one you want to go with, @ransome1.  Just let me know what you decide.

**Comment by ransome1** [comment] 2022-10-10 10:51
@zerodat could you send me the PR for both options? I still believe option 3 is the most intuitive and self explanatory, but I am open to give the `?` option a chance too, of course.

**Comment by TriggerDingus** [comment] 2022-10-12 16:20
I was just going to report this issue, though I hadn't connected the issue to only filtering on words beginning with "t" but this exactly explains what I've been running into. Kudos!

**Comment by zerodat** [comment] 2022-10-13 03:53
@ransome1 I will send you a PR for the "option 3" solution as soon as I can.  It would be easy except that I am away from home for the next two weeks.  I'll try to reconstruct the solution and send it sooner.  If that doesn't work out, I will send it as soon as I am back at home (about October 28 or 29).  Sorry for the delay.

**Comment by ransome1** [comment] 2022-11-06 10:52
@Saturo78 @aubreyz @TriggerDingus I merged @zerodat pull request and it should be part of the latest release 1.2.9. Could you please give it a try?

**Comment by ransome1** [comment] 2022-11-08 23:05
I havn't heart back from you guys, but double checked the implementation just now. It seems to work as expected. If this is not the case, please reopen here.

**Closed by ransome1** 2022-11-08 23:05 UTC
Labels: bug
