### ISSUE TITLE
Items marked Done show a week later 

### ISSUE THREAD

**Issue by velardevines** [ransome1/sleek#105] opened 2021-04-23 16:13 UTC
**Is it an actual bug?**
Yes

**Did you check if the bug has already been reported?**
Yes

**Describe the bug**

Item created today then marked Done today:

![Screenshot 2021-04-23 9 49 20 AM](https://user-images.githubusercontent.com/13563674/115897091-4beea200-a419-11eb-87a4-a16a01df707a.png)

Find all items marked Done today: 

![Screenshot 2021-04-23 9 47 23 AM](https://user-images.githubusercontent.com/13563674/115896806-09c56080-a419-11eb-880f-b5f75db58e74.png)

**To Reproduce**
1. Create a new item and Save.
2. Mark the item Done. 
3. Ctrl-F then type "x 2021-04-23" to show items marked Done today
4. See screenshot above. Items display next week. Recurring items show both today and next week.

**Do you see any error entries in sleeks developer tools?**
No errors in Log.  

**Expected behavior**
Done items to show on the actual day they were marked Done.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Chromebook Linux (Beta). ARM processor. 
 - Version of sleek: v 1.0.1
 - Source: Flathub

**Comment by velardevines** [comment] 2021-04-25 04:11
After looking again, this problem only happens for items with due dates and that are recurring. 

I can't see anything that I might be doing that is causing the date to display a week later than the Done date. But if anyone has any ideas about this, let me know what you think.

**Comment by ransome1** [comment] 2021-04-25 16:48
Hi @velardevines,

I checked it yesterday but wasn't able to reply until now.

So the recurring todos work three ways:
1. You have a todo with no due date, but a recurrence. Once this todo is set complete, another todo will be created. It will add the recurrence time frame to the date of completion.
2. A todo with a due date and a recurrence will automatically create a duplicate once the due day has been reached. It will add the recurrence time frame to the former due date, which will then become the new due date.
3. If a todo has a due date and a recurrence but is set completed before the due date has been reached, a duplicate will be generated. The new due date will be the date of completion plus the recurrence time frame and not the former due date (plus the recurrence frame).

So as long as the recurrence is set and the todo isn't deleted, but completed (those are two different things in sleek) a duplicate will always b created.

I hope it hasn't been described too confusing ;)

I wasn't able to reproduce your example from yesterday though, propably because I couldn't see a recurrence on the screenshots.

**Comment by velardevines** [comment] 2021-04-26 00:00
Hi @ransome1, thanks for explaining those use cases. I did not realize 1. was a valid use case and will start using it now that I understand it. 

My earlier attempts to explain the problem I see were confusing. Your patience is appreciated. I'll try again and hope to explain more clearly.

1) Create an item with due date today and 1w recurrence: 

![image](https://user-images.githubusercontent.com/13563674/116012740-a0487c00-a5e9-11eb-96fb-8fc5bcac8f85.png)

2) Result is two items. One item with due date today and a second item with due date one week later.  This is expected.

![image](https://user-images.githubusercontent.com/13563674/116013383-27e3ba00-a5ed-11eb-8e76-1a0ad93ac96d.png)

3)  Mark the item due today as Done. Result:

a) The item with due date a week in the future is still active- this is expected. 
b) The item with due date of today is Done - this is expected. 
c) However, a new item is created and is marked Done with a due date of 1 week in the future- this is what was unexpected. 

![image](https://user-images.githubusercontent.com/13563674/116013568-164ee200-a5ee-11eb-85f5-21adf19b79b8.png)

Here is what the third item on the above list looks like:

![image](https://user-images.githubusercontent.com/13563674/116013788-303cf480-a5ef-11eb-88f5-99471dabf475.png)

Maybe I am still not understanding the use cases. However, it seems this third item which is marked Done and has a due date 1 week in the future should not be created. 

Thanks again. Sleek is exceptional; I use it daily.

**Comment by ransome1** [comment] 2021-04-26 08:29
@velardevines, thanks! I found and fixed the issue. It will be released with v1.0.2

**Comment by ransome1** [comment] 2021-04-26 12:48
Hi @velardevines. Can I ask you to check v1.0.2 if the problem still persists? https://github.com/ransome1/sleek/releases/tag/v1.0.2

**Comment by velardevines** [comment] 2021-04-26 13:52
Hi @ransome1, I repeated steps 1, 2, and 3 as mentioned above. Unfortunately the result is unchanged.  Here are screenshots after step 3:

The item marked Done with due date 1 week in the future is still being created: 

![image](https://user-images.githubusercontent.com/13563674/116092826-5e5c1c00-a663-11eb-9da1-c57e961f5353.png)

Here is that item:

![image](https://user-images.githubusercontent.com/13563674/116093011-8d728d80-a663-11eb-802f-51fe817c18b0.png)

I am running v 1.0.2 on Windows 10. 

![image](https://user-images.githubusercontent.com/13563674/116093208-b8f57800-a663-11eb-9c39-f51ea5aadb54.png)

Is there any other information I can provide?

**Comment by ransome1** [comment] 2021-04-26 16:05
Hi @velardevines. Could you please list the exact inputs of your todos for the three steps in plain text, so I can reproduce it?

**Comment by velardevines** [comment] 2021-04-26 23:23
No problem @ransome1. If this is not what you need, explain it to me again.  :-) 

1) Create a todo with this content: "Task due:2021-04-26 rec:w" 
2) Mark that todo as Done.

That reproduces the problem.

3) The three todo items created by the two steps above have this content: 
a) "2021-04-26 Task due:2021-05-03 rec:w"
b) "x 2021-04-26 2021-04-26 Task due:2021-04-26 rec:w"
c) "x 2021-04-26 2021-04-26 Task due:2021-05-03 rec:w"

The todo item shown in 3) c) is what is not expected.

Thank you.

**Comment by ransome1** [comment] 2021-04-27 05:02
Thanks, could you please double check if you're using one of the Windows files from the release page? https://github.com/ransome1/sleek/releases/tag/v1.0.2

On my Linux machine and my Windows VM I' having difficulties reproducing the issue with the new release. 

If you're using the correct version and the issue is still existent, can you take a look at this video, if I'm doing it the same way(s) you're doing it?

https://user-images.githubusercontent.com/11188741/116187508-f28eb780-a725-11eb-8b61-5505b9d97edd.mp4

**Comment by ransome1** [comment] 2021-04-27 05:15
@velardevines , I think I might have found the reason for this mix up and need to apologize for it. But let's double check. So for whatsoever reason the Github CI process build a Windows binary from an old branch and added it to the release page. So there are basically three Windows files, 2 installer and 1 portable:
![image](https://user-images.githubusercontent.com/11188741/116188588-f58aa780-a727-11eb-955f-d7f12eeaeed7.png)

I downloaded the installer (sleek-1.0.2-Setup.exe) and the portable (sleek-1.0.2.exe) and I did not experience the issue. Then I found the second installer at the bottom of the list (sleek-Setup-1.0.2.exe) and using this one, your issue still is present. 

I'm going to remove the wrong installer now and would like to ask you to check one of the two Windows files left in the release list.

**Comment by velardevines** [comment] 2021-04-27 15:48
Yes, downloading the new v1.0.2 installer solved the problem. So, I checked Sleek v 1.0.2 on Windows 10 and also on the Flathub install on a Chromebook Linux (Beta) ARM install. Issue is corrected on both machines. 

I noted the apology @ransome1 but please understand is not necessary. What is life without trying; what is trying without mistakes; hmmm an existence I'd rather not experience. 

Thanks again for making Sleek!

**Comment by ransome1** [comment] 2021-04-27 17:46
Thanks for your feedback, @velardevines

**Closed by ransome1** 2021-04-27 17:46 UTC
Labels: bug
