### ISSUE TITLE
appendStartDate not working any more

### ISSUE THREAD

**Issue by dlaidig** [ransome1/sleek#432] opened 2022-10-24 20:53 UTC
**Is it an actual bug?**
Yes

**Did you check if the bug has already been reported?**
Yes

**Describe the bug**
Recently the creation data is not saved in new entries any more. In my `user-preferences.json` I see that `"appendStartDate": true` is still set.

**To Reproduce**
1. Set appendStartDate to true
2. Create new entry
3. Check if todo.txt contains the creation date.

**Do you see any error entries in sleeks developer tools?**
Should not be relevant.

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version of sleek: 1.2.8
 - Source: Flathub

**Comment by ransome1** [comment] 2022-11-01 11:08
@dlaidig thanks for reporting this. Could you please check, if this feature does work again in https://github.com/ransome1/sleek/releases/tag/v1.2.9-rc.1

**Comment by dlaidig** [comment] 2022-11-01 14:40
I was already about to write that it does not seem to have changed at all. Then I noticed it actually now works when creating issues via the dialog but not when using the "add as todo" button in the search bar (which I end up doing most of the time).

**Comment by ransome1** [comment] 2022-11-01 14:41
@dlaidig mmhh that's odd, let me look into it again.

**Comment by dlaidig** [comment] 2022-11-01 15:03
Oh, and it totally does seem to break setting priorities in the dialog, either by typing "(A)" manually or by using the controls. The date is put before the priority, and then the priority is interpreted as text. After some iterations of trying to change the priority, I ended up with `2022-11-01 (A) 2022-11-01 (A) 2022-11-01 (A) test issue`

**Comment by ransome1** [comment] 2022-11-04 10:18
I think I have to admit, that fixing this will be an ugly workaround. The root cause for this issue lies is the library, that parses the string into todo.txt objects. There is rewrite of this particular library going on at the moment and as soon as the it has been released, this issue will be fixed. As for now I won't continue working on fixing it, but the solution for this is near.

**Comment by dlaidig** [comment] 2023-07-23 09:28
Glad to see that you are still working on sleek, @ransome1. I'm looking forward to test v2.0 when it is a bit further along.  :)

I think this issue is still very much relevant and should be kept open.

**Comment by ransome1** [comment] 2023-09-12 12:40
Available in https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev9

**Closed by ransome1** 2023-09-12 12:40 UTC
Labels: bug
