### ISSUE TITLE
Marking recurring task as complete doesnt create new entry

### ISSUE THREAD

**Issue by elegantepictetus** [ransome1/sleek#169] opened 2021-06-20 20:23 UTC
**Is it an actual bug?**
Yes

**Did you check if the bug has already been reported?**
Yes it was reported but closed

**Describe the bug**
recurring task completion doesnt create new task

**Do you see any error entries in sleeks developer tools?**
No error entries

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04
 - Version of sleek 1.0.6-2
 - Source: SourceForge

**Comment by ransome1** [comment] 2021-06-20 20:31
@elegantepictetus . Thanks for pointing it out, it will be fixed in the next release. If you need this function, please go back to 1.0.6-1, until 1.0.7 is going to be released (soon).

**Comment by ransome1** [comment] 2021-06-22 10:01
@elegantepictetus , can you please check if this is solved on your side in https://github.com/ransome1/sleek/releases/tag/v1.0.7?

**Comment by rzelnik** [comment] 2021-06-23 08:39
I have v1.0.7 installed from .deb file. Each time I click on a recurring task with due date: today, it creates a finished task, but the active task with due date: today still remains.

**Comment by ransome1** [comment] 2021-06-23 08:44
@rzelnik: this is what's suppose to happen:
![Peek 2021-06-23 10-44](https://user-images.githubusercontent.com/11188741/123065988-f3835300-d40f-11eb-9451-bb9f38d50f89.gif)

Can you confirm this is not happening on your side?

**Comment by rzelnik** [comment] 2021-06-23 09:06
With some tasks it works like in your screenshot. With some tasks the today's task remains. I will investigate what's the difference and will let you know.

**Comment by rzelnik** [comment] 2021-06-23 09:17
It has something to do with the duplicates in the todo.txt files. When I remove the broken/duplicate task and create it again, usually then it works as expected.

**Comment by ransome1** [comment] 2021-06-23 09:23
I am not sure if I understand. I cannot see a broken or duplicate task, when I set the first complete.

**Comment by rzelnik** [comment] 2021-06-23 10:18
Never mind, not that big issue.

**Comment by ransome1** [comment] 2021-06-24 08:39
@elegantepictetus , @rzelnik , I assume it is working again, at least in https://github.com/ransome1/sleek/releases/tag/v1.0.7 it should :) If there still is an issue, please report back here and we will reopen.

**Comment by rzelnik** [comment] 2021-06-24 14:04
I got it. The strange behavior occurs when there is a recurring task in a line before another task.

```
2021-06-24 todo 1 due:2021-06-24 rec:d
2021-06-24 todo 2
```
When clicking on a recurring task ("todo 1") as done, it adds a finished task in a todo.txt file, the existing unfinished file remains, and the "todo 2" disappears. So the output after clicking on a recurring task is like this:

```
2021-06-24 todo 1 due:2021-06-24 rec:d
x 2021-06-24 2021-06-24 todo 1 rec:d due:2021-06-24
2021-06-24 todo 1 rec:d due:2021-06-25
```


https://user-images.githubusercontent.com/610651/123276832-d3ce5680-d505-11eb-8095-b91c8a95c980.mp4

**Comment by zerodat** [comment] 2021-06-28 06:05
@ransome1, reopening this issue, because I've also seen this bug, in a similar case to the one that @rzelnik described.  I have a PR #185 that fixes the bug.

To reproduce the bug in sleek 1.0.7, use this todo.txt:
```
2021-06-25 task that repeats due:2021-06-26 rec:1d
x 2021-06-27 a finished task due:2021-06-27
```
Opened in sleek you will see this:
![Screenshot from 2021-06-27 22-04-24](https://user-images.githubusercontent.com/81216634/123583143-f8d7f900-d793-11eb-8770-b76e52d04665.png)

And then after clicking the "complete" button on the first task, you will see this:
![Screenshot from 2021-06-27 22-05-05](https://user-images.githubusercontent.com/81216634/123583194-0beac900-d794-11eb-97ba-599df3177245.png)

Note that the original task is still there, as well as the next occurrence (dated "Tomorrow"), and also note that the finished task has been overwritten by the finished occurrence of the repeating task.

This has to do with the method used to find duplicate todos by string matching in the items array using toString().  toString() is inherited from jsTodoTxt and it turns out that its behavior is a little tricky ... it depends on the list of extensions, and specifically on the order in the list of extensions, that is passed to the jsTodoTxt function used to create the todo object.  I will give more details in the PR that I am submitting to fix this bug

**Closed** 2021-07-02 05:05 UTC
Labels: bug
