### ISSUE TITLE
relative due dates off by one: very strange 

### ISSUE THREAD

**Issue by rzw** [ransome1/sleek#554] opened 2023-10-29 19:01 UTC
## Bug Report

**IMPORTANT:**
Please follow this template strictly when reporting bugs. Providing detailed and accurate information helps the development team to understand and address the issue effectively.

**App Version:** [1.3.2-rc1]

**Platform:** [Windows 10]

**Installation Method:** [Portable: Direct Download]

**Bug Description:**
[I just noticed it today. I have no idea if it is related to this but clocks were adjusted tonight, daylight saving time is over. due:0d is still today but all others are off by one. So due:1d is also today but used to be tomorrow, due:2d is now tomorrow]

**Steps to Reproduce:**
1. [just create new item with a relative due date using 0d, 1d, 2d ]

**Expected Behavior:**
[0d used to be and should be today, 1d used to be and should be tomorrow ]

**Actual Behavior:**
[off by one, see bug description]

**Additional Information:**
- [I'm curious whether you can reproduce this. I'm completely surprised and puzzled.]

**Screenshots:**
[If applicable, include screenshots that demonstrate the bug.]

**Comment by rzw** [comment] 2023-10-30 05:55
All is fine today.
As I said: very strange.
The two test events I created yesterday (due:0d and due:1d) are now seperated and listed in today and tomorrow. Yesterday both were listed in today despite there different relative due dates. My only clue is some malformed daylight saving time logic.
The adjustment was yesterday.

**Comment by ransome1** [comment] 2023-10-30 06:54
It could be some issue with how dates are handled by sleek in version 1.x. 

Since in 2.x I've switched to a different library to handle the date calculation, I'm curious if this still happens. 

The best would be if you would be able to reproduce this behaviour somehow and then to check if the same thing happens with the latest developer preview, which you can find in the GitHub releases.

**Comment by rzw** [comment] 2023-10-30 08:00
I can't do this right away. I'll do this on an older laptop. Don't want to mess around adjusting the wrong date on my PC. But I think you're right. Relative dates require calculation and since todo.txt has no time it could be that per default it's 0h (12 AM). So subtracting an hour (wherever and why this happens) on the day of time change puts that event into the previous day

**Comment by ransome1** [comment] 2023-10-30 20:53
@rzw 2.0.0 has been released on GitHub. Please feel free to provide your feedback based on it.

**Comment by rzw** [comment] 2023-10-30 22:23
Exciting 🤩

**Comment by ransome1** [comment] 2023-11-01 13:48
@rzw is this still an issue? If not feel free to close the issue, please.

**Closed** 2023-11-01 15:30 UTC
Labels: bug
