### ISSUE TITLE
Auto detection of Russian language crashes app on 1st start

### ISSUE THREAD

**Issue by kden416** [ransome1/sleek#358] opened 2022-04-04 10:34 UTC
Sleek version 1.1.7 / 1.1.8-rc2 and Microsoft Store version won't start.
Terminal output have error:
`
Persisted data located at: C:\Users\user\AppData\Local\Programs\sleek\user-preferences.json
TypeError: Cannot create property 'functionName' on string 'Error in getTranslations(): TypeError: Cannot read properties of undefined (reading 'translation')'
    at createWindow (C:\Users\user\AppData\Local\Programs\sleek\resources\app.asar\src\main.js:896:24)
[12180:0404/103117.376:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is
`

**Comment by ransome1** [comment] 2022-04-04 10:52
@kden416 thanks for reporting this. I installed it from Windows Store and didn't see any error popping up. Are upgrading from an old version? And if so would mind sharing your preferences file with me? It's located at C:\Users\user\AppData\Local\Programs\sleek\user-preferences.json and you can either post it here or send it to ransome [at ] duck dot com.

Also can you backup this file and then delete the original one and try to start sleek again?

**Comment by kden416** [comment] 2022-04-04 11:03
1. user-preferences.json deletion has no effect
2. [v1.1.8-rc.3](https://github.com/ransome1/sleek/releases/tag/v1.1.8-rc.3) started, but blank window with controls.

user-preferences.json:
`{
  "width": 1100,
  "height": 700,
  "horizontal": 160,
  "vertical": 240,
  "maximizeWindow": false,
  "darkmode": true,
  "notifications": true,
  "useTextarea": false,
  "compactView": false,
  "matomoEvents": false,
  "drawerWidth": "500",
  "showDueIsPast": true,
  "showDueIsFuture": true,
  "showDueIsToday": true,
  "showHidden": false,
  "showCompleted": true,
  "sortCompletedLast": false,
  "invertSorting": false,
  "zoom": "100",
  "tray": false,
  "showEmptyFilters": true,
  "sortByFile": false,
  "dismissedNotifications": [],
  "dismissedMessages": [],
  "hideFilterCategories": [],
  "files": [],
  "sortBy": [
    "priority",
    "due",
    "contexts",
    "projects",
    "date"
  ],
  "selectedFilters": []
}`

**Comment by ransome1** [comment] 2022-04-04 11:08
@kden416 what language did you set in Windows itself?

**Comment by kden416** [comment] 2022-04-04 11:09
@ransome1 my language is russian

**Comment by ransome1** [comment] 2022-04-04 11:11
That's odd. Let's see if I can reproduce this somehow.

**Comment by ransome1** [comment] 2022-04-04 11:34
@kden416 are you experiencing the same issues when you switch your language to english?

**Comment by kden416** [comment] 2022-04-04 11:48
@ransome1 apparently, problem with system language. If I set english as system language, all works fine with **1.1.7 and 1.1.8-rc2** versions.

**Comment by ransome1** [comment] 2022-04-04 12:25
I think the problem is that the auto detection of the russian language doesn't work and that the default fallback (english) for some reason is not being set. But this I think I can fix somehow. I will add this to the backlog, thanks for reporting this.

As a temporary workaround you can do what you already did: Start sleek with your Windows set to english (like this sleek will detect the english language and persist it in its settings) and then switch back to Russian.

**Comment by kden416** [comment] 2022-04-04 12:27
Thank you for this amazing app!

**Comment by 7loro** [comment] 2022-07-08 18:37
tested on Sleek 1.2.1 on mac os.
~/Library/Application\ Support/sleek/user-preferences.json
In the user preference json, there is `"language": "ko"` which is automatically added by system.

Same error is occurred
```
TypeError: Cannot read properties of undefined (reading 'translation')
    at createWindow (/Users/casper/Tools/sleek/src/main.js:629:75) {
  functionName: 'createWindow'
}
```

To fix issue as a workaround, change language value in ~/Library/Application\ Support/sleek/user-preferences.json `"language": "en"` . Now It works.

**Comment by ransome1** [comment] 2022-09-27 09:35
@kden416 @7loro could you guys take a look at this test release (https://github.com/ransome1/sleek/releases/tag/v1.2.2-rc.3) and give me a feedback if it solves the issue on your side?

**Comment by 7loro** [comment] 2022-09-27 09:51
> @kden416 @7loro could you guys take a look at this test release (https://github.com/ransome1/sleek/releases/tag/v1.2.2-rc.3) and give me a feedback if it solves the issue on your side?

tested on Sleek 1.2.2-rc.3 on mac os.
Now it works fine 👍 

When I install app, In the user preference json (~/Library/Application\ Support/sleek/user-preferences.json), there is "language": "en" which is automatically added by system even if my system language is korean. There is no crash now.

**Comment by ransome1** [comment] 2022-10-16 16:40
I'm closing here as this has been resolved.

@7loro if you have some time on your hands and would like to use sleek in your native language, you can simply translate this file (https://github.com/ransome1/sleek/blob/master/src/locales/en/translation.json) and send me a pull requestes. Makes you a contributor and sleek one language richer :)

**Closed by ransome1** 2022-10-16 16:40 UTC
Labels: bug
