### ISSUE TITLE
Main Window does not appear in windows tray and it cannot be Alt+Tab

### ISSUE THREAD

**Issue by buscon** [ransome1/sleek#221] opened 2021-07-20 08:04 UTC
**Is it an actual bug?**
yes

**Did you check if the bug has already been reported?**
not for Linux Mint. There is someting similar for windows: https://github.com/ransome1/sleek/issues/170

**Describe the bug**
After starting sleek, it is not possible to:
1. Alt+Tab and switch the focus to it
2. recover the app from the tray
The only way to get back to the window is to hid the other windows which are covering sleek.

**To Reproduce**
1. start sleek
2. move any other window on top of the sleek window
3. it is not possible to catch the sleek window without hiding the other windows.

**Do you see any error entries in sleeks developer tools?**
No

**Expected behavior**
I expect to be able to catch the window again, when it is hide by another window

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2
 - Version of sleek 1.0.9
 - Source: Github

**Comment by zerodat** [comment] 2021-07-20 16:04
@buscon I am running Linux Mint 20, cinnamon 4.6.7 and the alt+tab works fine for me with sleek 1.0.9 (AppImage).  Are you using cinnamon or another desktop environment?

**Comment by buscon** [comment] 2021-07-20 18:11
hi @zerodat 

thanks for your answer. I am running Mint 20.2 with cinnamon 5.0.5. I installed the .deb package. I tried the last 1.10 rc and it has the same problem.

**Comment by zerodat** [comment] 2021-07-20 19:25
@buscon I will try a dpkg installation as soon as I have time.  Could you try the appimage?  It is very easy: just download it (let's say the file is `sleek.appimage`), make it executable with `chmod +x sleek.appimage` and then run it with `./sleek.appimage`.

Thanks.

**Comment by buscon** [comment] 2021-07-20 19:33
@zerodat I just tried with the appimage and it has the same problem. Maybe it has something to do with the cinnamon version?

**Comment by zerodat** [comment] 2021-07-20 20:22
OK, I will try to build a Mint 20.2 system and see if I can reproduce this.  Thanks for testing the appimage!

**Comment by zerodat** [comment] 2021-07-20 23:31
@buscon I installed a fresh Linux Mint 20.2 system with Cinnamon 5.0.4, and the Alt-Tab worked fine with sleek-1.0.9.AppImage.  And then I upgraded to Cinnamon 5.0.5 and that appears to work properly as well.  I'm not sure what else to try.

Can you check your system log files to see if there are any errors that might be relevant?  I wonder if there are any Cinnamon configuration options that might be causing this on your system.

**Comment by ransome1** [comment] 2021-07-21 04:56
@zerodat thanks for helping out here!

@buscon Im not on Linux Mint but on Arch Linux, as well as MacOS and Windows. I can't reproduce this either.

**Comment by buscon** [comment] 2021-07-21 07:22
@zerodat @ransome1 
thanks for your feedback. I cannot see any relevant error in my logs. In case I find out something, I will report it.

**Comment by ransome1** [comment] 2021-07-21 07:49
I fixed a bug in the latest test release. After switching to `tab mode on` sleek could not be switched back to `off`. It's propably not related to your issue, but it cannot hurt to try out the latest release: https://github.com/ransome1/sleek/releases/tag/v1.1.0-rc.4

Let me know :)

**Comment by buscon** [comment] 2021-07-21 09:01
I think I figured it out in the meanwhile.

In the settings there is a "Minimize to the tray bar" setting. I tried to turn that on, but it was always showing it as off (see screenshot).
![Screenshot from 2021-07-21 10-58-39](https://user-images.githubusercontent.com/2972257/126461682-4d5afb57-a203-4f12-82a4-ebe20be20571.png)

Now I checked the json settings file `~/.config/sleek/user-preferences.json` and it was set to true:
`"tray":true`
I closed sleek, change the setting to false:
`"tray":false`
and now I can see sleek in the Alt+Tab

I guess the question is now, why do I see the setting as turned off, even though it is set to true.

**Comment by ransome1** [comment] 2021-07-21 09:02
@buscon did you read my previous post? ;)

**Comment by buscon** [comment] 2021-07-21 09:04
> @buscon did you read my previous post? ;)

@ransome1 yes, I did, but I though that `tab mode on` is another setting, isn't it?
Anyway, I can try the last rc release and check it.

**Comment by buscon** [comment] 2021-07-21 09:08
ok, now I see. your bugfix is fixing my problem too :)
It works fine on rc.4!
thank you!

**Comment by ransome1** [comment] 2021-11-05 09:16
@buscon I'm closing here as I assume this issue is gone, right? If not, just report back here.

**Closed by ransome1** 2021-11-05 09:16 UTC
Labels: bug

**Comment by buscon** [comment] 2021-11-05 09:23
correct, thanks!
