### ISSUE TITLE
email address incorrectly parsed as a context (@ symbol)

### ISSUE THREAD

**Issue by mshuflin** [ransome1/sleek#631] opened 2024-01-11 08:49 UTC
### Important ###
Please follow this template strictly when reporting bugs. 

**App Version:** [_Enter app version here_]
sleek v2.0.5
**Platform:** [_Windows / macOS / Linux_]
macOS Sonoma, 14.2.1, M2
**Installation Method:** [_App Store / Direct Download / Other_]
Github
**Bug Description:**
[_Provide a clear and concise description of the bug you encountered._]
using the @ symbol causes the attributes page to list an incorrect context
**Steps to Reproduce:**
1. [_List the steps to reproduce the bug. Be as specific as possible._]
 - Write a todo that contains an email address (e.g. steve@apple.com)
 - look in the contexts section of the attributes filter
 - see the email addresses domain (e.g. apple.com) displayed as a context
**Expected Behavior:**
[_Explain what you expected to happen._]
Only contexts should be displayed, maybe only when the @ symbol is preceded by a space or starting a new line?
**Actual Behavior:**
[_Explain what actually happened._]
see above
**Screenshots:**
[_If applicable, include screenshots that demonstrate the bug._]
![Screenshot 2024-01-11 at 4 48 23 PM](https://github.com/ransome1/sleek/assets/53985056/3d18e674-f196-49db-91b8-242485978bea)
![Screenshot 2024-01-11 at 4 48 13 PM](https://github.com/ransome1/sleek/assets/53985056/fa8c1f82-0390-404f-b7ea-a352749062d7)

**Comment by ransome1** [comment] 2024-01-11 09:08
@mshuflin I think this is a duplicate of https://github.com/ransome1/sleek/issues/617

**Comment by mshuflin** [comment] 2024-01-11 09:12
Yep, sorry about that

**Comment by ransome1** [comment] 2024-01-11 09:17
@mshuflin feel free to close the issue, we will fix this over at #617

**Closed** 2024-01-11 10:33 UTC
Labels: bug
