### ISSUE TITLE
Keep inactive filter options visible

### ISSUE THREAD

**Issue by freder** [ransome1/sleek#107] opened 2021-04-25 11:36 UTC
when filtering, I think it would be nicer from a UX point of view if the inactive/non-selected items remained visible (but greyed out) instead of them disappearing.

(as a new user) it might be just me but right now the filter state is not super clear (visually). I would prefer it to be more explicit -> _"those are all the options, of which these n items are selected"_. -- hope that makes sense.

**Comment by ransome1** [comment] 2021-04-25 16:52
Hi @freder , I do agree and it has been on my personal roadmap for quite some time. It has some conceptional and programmatical challenges, and so far there were many other todos I needed to work on that were more pressing. 

I added it to sleeks official roadmap for v1.1. Thanks for proposing it.

**Comment by ransome1** [comment] 2021-05-27 16:38
Hi @freder, this feature request is part of this development version and I would really appreciate your help on testing it: https://github.com/ransome1/sleek/releases/tag/v1.0.5-1

Also, if you're interested in bulk renaming contexts, projects and priorities, you can help me by testing that feature and sharing your feedback here: https://github.com/ransome1/sleek/issues/47

**Comment by 9z0** [comment] 2021-05-28 12:48
While I understand the usefulness of this, it is better if it is optional. If you have a lot of projects/contexts, it makes further filtering a scrollfest :)

Also, it would help if we could resize the project/context buttons on the left side (independent of the universal zoom slider). This way, I can fit more in the same space.

**Comment by ransome1** [comment] 2021-05-29 10:16
@9z0, all that would mean more toggles, dropdowns or checkboxes that will confuse many and only benefit a few. 

sleeks is a simple app for a simple purpose and therefor should only have a simple GUI with as little customization as possible. I'm aware some users disagree on that. 

But in my humble opinion there are already way too many settings. When looking at the telemetry data some users are kindly providing, I can see that many settings and even features are barely even used.

Anyhow, I decreased the size of the of the filter buttons in the side bar and adjusted them to the size of the filters in the todo list for the **compact mode**. If you're handling a lot of filters and todos, this can be of help to you. Also, you might have already spotted it but let me point out that you're able to adjust the width of the side bar using a handle which is placed on the right edge of the side bar. This too could prevent the scrollfest on your setup.

I'm actually curious on sleeks performance dealing with this many todos. Is it feasible or would a lazy loading option on the table make any sense?

**Comment by 9z0** [comment] 2021-05-29 14:03
Thanks.

I understand and accept your vision for Sleek.

A good established workaround is text-based (as opposed to graphical) customization. You don't have to expose the option to the regular user in the UI.

Google Chrome has a strong emphasis on simplicity of UI and ease of use. Yet it supports a ton of launch parameters.

For sleek, you can add support for all needed option to `user-preferences.json` or (for simplicity of editing) an INI config file that sleek reads on startup. Then tell interested users what these options do in a text file or here on GitHub or so.

As for performance, I was meaning to open an issue for that, but I thought I'd wait a bit until the other issues are taken care of first :)

Performance started to degrade noticeably for me at around 500 todos, and worsens rapidly as they increase.

The main issue is the transition on applying/removing filters (especially on removing). This correlates with the size of the target list. For example, a filter that has a positive match of 500 todos loads slower than a filter with 250 todos.

The same behavior can be noticed on using the search bar. The first character you type takes the longest to show results. The second is faster and the third even faster and so on.

Once the target list (of whatever size) is loaded, performance is acceptable. For example, the edit box loads as fast, but if you add/change something, the list has to be reloaded again, with delay proportional to its size as mentioned before.

**Comment by 9z0** [comment] 2021-05-30 19:27
I am not sure if I should open a new issue but I want to report the following:
- Click a filter (e.g. a project than has n (e.g. 1) todo.
- Edit that todo by removing that project from it. This will make that project disappear.
- Alternatively, choose a project than has >1 todo, but combine with another filter so that only one todo is shown, then remove the project from the visible todo. In that case, the project won't disappear, but will show 0.
- In both cases, you can't unselect (click) that filter. You'd have to click "reset all" or undo other filters until that project has a positive number.
- Suggested solution: there are multiple, but the most natural in my opinion is to keep active filter buttons under the search bar (like [here](https://graphicdesign.stackexchange.com/questions/13662/photoshop-how-to-create-buttons-that-look-subtly-pushed)):
    - each button with its own little x to remove.
    - one button at the beginning/end to remove all filters (but not search).
    - a circled x at the right end of the search bar to clear search (think search engines)
- This solution has the following benefits:
    - allow splitting search from filters (the both or nothing approach was a bit annoying to be honest. I keep copying my search to reapply after clearing filters).
    - filters always show is much clearer than having to look up and down (or in my case, scroll up and down) the filters list to find out where I am.
    - clear button(s) are not at the end of the list which is often hidden; especially as inactive filters are always shown.
    - it solves in the case described here (hidden/zero filters), and without having to play with shades to signify still-selected inactive filter.

**Comment by ransome1** [comment] 2021-06-01 07:28
@freder, this has been released with https://github.com/ransome1/sleek/releases/tag/v1.0.5. As I havn't heard from you in a while, I'm closing here.

**Closed by ransome1** 2021-06-01 07:28 UTC
Labels: feature request

**Comment by 9z0** [comment] 2021-06-01 09:39
Should I split the suggestions above in a separate issue or will you take note of them?
- Text-based customization (no UI option clutter).
- Filter bar under the search bar (detailed in my previous post).

**Comment by ransome1** [comment] 2021-06-01 10:37
@9z0, the behavior you're describing is clearly a bug. I can either put it on my own backlog or you create a separate bug ticket, so we can add it to sleeks Github project and discuss it during development.

Your suggestion on the selected filters is not a bad one and in general I like it. But it duplicates the filter drawer function in a sense and would mostly serve few power users like you, that have huge filter lists, while bloating the UI. 

Instead I suggest a setting named "showEmptyFilters" (default true) that, when set to false, hides all filters which have a count of 0.

I would implement it as a toggle in the view drawer to track if this setting is actively being used. If not, the settings toggle will be removed from the view drawer later on, but remains active and can be used in the `user-preferences.json`. What do you think about this?

**Comment by 9z0** [comment] 2021-06-01 10:48
That would be a fair compromise. I would suggest also maybe moving the "clear all" button to the top.

For any behavior that you don't want to make the default or even a visible option, a json-only option is a good solution for me, including moving the "clear all" button.

**Comment by 9z0** [comment] 2021-06-04 20:57
> But it duplicates the filter drawer function in a sense and would mostly serve few power users like you, that have huge filter lists, while bloating the UI.

I keep thinking about this and you are true that a small percentage of users would _need_ it.

Yet, I can't get over how clearer it would make things in my case – _together with_ the side panel projects. The duplication itself is useful for me, since each provides certain information much better than the other (I use sleek for much more than todos).

I don't want to burden you and I really thank you for sleek as it is. So, if you find some time and is not too much effort to add this "active filters" row (disabled by default and with text-only toggle), I would really appreciate it!

**Comment by ransome1** [comment] 2021-06-04 21:08
@9z0, not sure if I have mentioned it already, but in the view side bar there is now a first version of the discussed toggle, that will sleek let fall back to the previous behavior where empty filters are hidden. It still has some glitches as the implementation, like always even minor changes, can have unexpected side effects. In a nutshell: try not to use the category headline filter.

I assume you already found the keyboard shortcut for removing all filters? Might come in handy as well.

**Comment by 9z0** [comment] 2021-06-04 21:46
I didn't know about either. Thanks for letting me know! I saw the changelog but didn't realize they became single character (which is nice).

This should help a lot. Thanks!

**Comment by 9z0** [comment] 2021-06-14 14:11
> Anyhow, I decreased the size of the of the filter buttons in the side bar and adjusted them to the size of the filters in the todo list for the **compact mode**.

It reverted with 1.0.6 😕

**Comment by ransome1** [comment] 2021-06-18 08:07
The compact view received some minor adjustments in general. It is suppose to look like this:
![image](https://user-images.githubusercontent.com/11188741/122528581-c7855d80-d01c-11eb-9681-ed3af82e8607.png)

Whereas the regular mode should look like this:
![image](https://user-images.githubusercontent.com/11188741/122528664-df5ce180-d01c-11eb-9d04-ba86e85d2bc0.png)

This should be part of 1.0.6-1. Please let me know if it looks different on your side.

**Comment by 9z0** [comment] 2021-06-18 20:51
It looks alright. I would do a few touches, but it is a personal thing.

However, there is a couple of issues with popup projects on edit:

1. The list doesn't have a left margin.
![a](https://user-images.githubusercontent.com/78097210/122614271-a35e6680-d086-11eb-9c6f-c4e9c6c9b757.png)

2. Unscrollable.
3. The filter panel insists on starting closed (or reload/opening the app), even though "filterDrawer":true and "viewDrawer":true

**Comment by ransome1** [comment] 2021-06-19 06:03
Thanks for pointing it out, this one has slipped quality control ;)

**Comment by ransome1** [comment] 2021-06-19 15:36
Except 2., the issues should have been fixed in 1.0.6-2. Also the size of the buttons in the auto complete container are now adjusted to the ones in the filter side bar, both in regular and in compact mode.

**Comment by 9z0** [comment] 2021-06-20 02:15
I can confirm.

But now, with empty filters off, the whole filter bar and its icon disappear if all are empty (because you typed something that doesn't exist in the search bar for example) 🙃

**Comment by ransome1** [comment] 2021-06-20 05:10
@9z0, it is intended to hide the whole filter function when no filters are present, so nobody needs to see an empty filter bar.

With the "Empty Filters" option, I see why it can be problematic for instance in the case you're describing. I was able to reproduce this using the full text search and this case can be fixed easily. Did you find other use cases, that provoke this behavior as well?

It would also be an option to leave the three categories headlines always visible with a little "No filters for this category" box below, to prevent this scenario.

**Comment by 9z0** [comment] 2021-06-24 20:56
> It would also be an option to leave the three categories headlines always visible with a little "No filters for this category" box below, to prevent this scenario.

Any chance for such an option soon? This happens too often to me. One typo in search and filters are hidden. And I can't press `B` because I am in the search bar!

Thanks

**Comment by 9z0** [comment] 2021-07-01 21:39
I was hesitant to ask again because, on one side, this problem is very irritating, and on the other side, I understand that you have a lot on your hand and other priorities.

I'd like to point out that [custom CSS](151) would allow me to make a temporary workaround until you got the time for a proper solution! 😉

###### <sup>_So maybe pump [that](151) issue a bit on your todos?_</sup> 🙂

**Comment by ransome1** [comment] 2021-07-02 04:30
@9z0 it is unfortunately not only a quickfix with CSS but it comes with a bit of restructering the how the filters are being built in Javascript combined with minor enhancements to the GUI. It's on my list as the next task for further visual improvements and should be done in 1.0.9.

**Comment by 9z0** [comment] 2021-07-02 12:12
Great! Can't wait!
