### ISSUE TITLE
Chinese and Japanese translations

### ISSUE THREAD

**Issue by nutnutwin** [ransome1/sleek#141] opened 2021-05-30 08:19 UTC
Translation to Chinese(Native)/Japanese(Near Native)
Should I contact author? @ransome1 

Thank you

**Comment by ransome1** [comment] 2021-05-30 08:39
Hi @nutnutwin. Chinese and Japanse translations would be amazing. To do so, the only thing you would need to do is to fork sleek and start doing the translations based on https://github.com/ransome1/sleek/blob/master/src/locales/en/translation.json.

The Chinese translations for instance would then need to be put into https://github.com/ransome1/sleek/blob/master/src/locales/cn/translation.json and a pull request would need to be created by you, so you can be officially be listed as a contributor. 

Alternatively or if you're not familiar with the Github process, you can just download https://github.com/ransome1/sleek/blob/master/src/locales/en/translation.json, do the translations in separate JSON files and send them to me by email (ransome@uber.space). I would then take care of the rest.

**Comment by nutnutwin** [comment] 2021-05-30 09:34
@ransome1 Great
not very familiar with GitHub Fork, but will try
If not successful, will let you know, and send the json to you.

**Comment by ransome1** [comment] 2021-05-30 19:34
@nutnutwin, I assume you are working on a computer, that has a Chinese font installed? Then please feel free to try out this pre-release of v1.0.5, see your translations in action and share your feedback :)

https://github.com/ransome1/sleek/releases/tag/v1.0.5-5

Let me know if it works or if anything is missing. I'll check it tomorrow in detail on a Windows VM (Windows has a Chinese font installed per default).

**Comment by nutnutwin** [comment] 2021-05-30 21:25
@ransome1 Great! I tried it out, and found
- some problems on my side
	Will fix and request pull
- some probelms with font/zoom/layout
	Will report as issue

**Comment by nutnutwin** [comment] 2021-05-30 21:48
<img width="352" alt="20210531_Mon -064504" src="https://user-images.githubusercontent.com/34512273/120120943-c27e7c80-c1db-11eb-81f4-2d69da974c7b.png">

@ransome1 Hi I am not extremely familiar with font mechanism
but it seems to be using a fallback font for some of the characters

wonder which font is specified? (is it app-wide font?

**Comment by ransome1** [comment] 2021-05-31 06:50
@nutnutwin, I added four fallback fonts which, according to the interwebs, are capable of handling SC without any issue. Namely:
1. "Arial Unicode MS"
2. "Microsoft JhengHei"
3. "微軟正黑體"
4. "Microsoft YaHei"

So the whole fallback chain now looks like this in this order: "FreeSans", Helvetica, "Arial Unicode MS", Arial, "Noto Sans", "DejaVu Sans", "Microsoft JhengHei", "微軟正黑體", "Microsoft YaHei", sans-serif;

If all those fonts are not available on the users computer, the next fallback will be a sans-serif font selected by the OS and that will eventually lead to the behavior we can see on your screenshots. But I assume that Chinese users will most likely have either one of te four fonts installed or a proper sans-serif fallback font installed.

Also I enhanced the due date and recurrence picker function, responsible for settings the width of those elements dynamically. I tested it on my Win 10 Vm and it looked good. Can you confirm this?

I replaced the old new builds with new ones: https://github.com/ransome1/sleek/releases/tag/v1.0.5-5

**Comment by nutnutwin** [comment] 2021-05-31 07:08
@ransome1 
I would love to try, but the URL does not contain any binary?

**Comment by ransome1** [comment] 2021-05-31 07:12
I forgot to include your latest translation file and the new version is being built right now.

**Comment by ransome1** [comment] 2021-05-31 07:29
Ok, the new builds are up: https://github.com/ransome1/sleek/releases/tag/v1.0.5-5

This is the portable zipped version: https://github.com/ransome1/sleek/releases/download/v1.0.5-5/sleek-1.0.5-5.zip

**Comment by nutnutwin** [comment] 2021-05-31 07:55
![20210531_Mon -165423](https://user-images.githubusercontent.com/34512273/120160157-e7510f00-c230-11eb-8bd3-39ab801520af.png)
Still some Characters showing improperly
possible to dump a log where your font is falling back to? 
---

BTW the new/edit Button shows fine

**Comment by ransome1** [comment] 2021-05-31 08:23
Can you tell me which signs are showing improperly? Do you see a pattern? For instance "only when set bold" or only when sign is in a headline?

To see which font is actually rendered, you could take a look into the Chromium Developer Tools. In sleek, press Alt and the top menu will show up. In "About" there is an option to open the Developer tools.

Within in dev tools you need to use the element selector and select an element, that contains a font. Then if you select the tab "Computed", you need to scroll to the bottom and the font, that actually has been rendered, will be listed. 
![image](https://user-images.githubusercontent.com/11188741/120163693-0f714b80-c1fa-11eb-858c-f67a494c6dba.png)

Described with more detail here: https://stackoverflow.com/questions/884177/how-can-i-determine-what-font-a-browser-is-actually-using-to-render-some-text/20830300#20830300

**Comment by ransome1** [comment] 2021-05-31 08:36
This is the font rendered on my Windows 10 VM:
![image](https://user-images.githubusercontent.com/11188741/120165340-c3270b00-c1fb-11eb-92fd-293a244f8c28.png)

And when I recreate your screenshot above, on Win10 it looks like this:
![image](https://user-images.githubusercontent.com/11188741/120165539-f8335d80-c1fb-11eb-8a5f-6b6a9093574b.png)

**Comment by ransome1** [comment] 2021-05-31 08:48
@nutnutwin, I also found an old Windows 7 laptop in pretty much default configuration. This is what sleek in 1.0.5-5 looks like in Win7
![image](https://user-images.githubusercontent.com/11188741/120167163-b3a8c180-c1fd-11eb-915e-dc9ab73e551a.png)

Does this look correct?

**Comment by nutnutwin** [comment] 2021-05-31 08:52
Both your Windows 10 and Windows 7 Screenshot looks perfectly fine
In my Screenshot, "任务列表" on the Top Left is not shown properly, with "务" falling back
It is highly likely just my problem, as I tweak with system font a lot. 

for example, 
- Force all font to my liking
- Use specific language for non-unicode application(for running Japanese language old apps)

**My bad.** 

Could you please provide some info on your VM configuration?(or just out of box?) I might try that later, Thank you. 
@ransome1

**Comment by ransome1** [comment] 2021-05-31 08:55
It is this VM out of the box: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/

Font settings cannot be changed within this VM, as it is restricted. I assume this is the default Win10 configuration. But I can't say fo sure.

**Comment by nutnutwin** [comment] 2021-05-31 09:00
Great!
Will find some time for the debug tools(not familiar with web developing)

Once I pin down the problem will report here

**Comment by ransome1** [comment] 2021-05-31 20:52
@nutnutwin, I was thinking about wrapping up the 1.0.5 tomorrow and deploy it through all channels. Should I wait a bit longer for the Japanese translations or shall we put them into the next release (1.0.6)?

**Comment by ransome1** [comment] 2021-05-31 21:01
@nutnutwin, I have another question for you. Are you working on an OS that is set to Chinese? I was wondering if, after deleting sleeks config files, the Simplified Chinese translation is automatically chosen, or if the fallback to English sets in.

**Comment by nutnutwin** [comment] 2021-05-31 21:07
@ransome1 as I mentioned(I think you saw it already) I will do the Japanese translation after you put the business entry to avoid misunderstanding. 
Not very gitty though...

For personal PC OS(where problem is produced), I believe I either
- clean installed English OS(this is the same env with you I believe)
- Specified Chinese on installation, and installed English as a language pack(and applied to UI)

I have 2 PCs @Company with Clean English Installation, I will check if they work properly

**Comment by ransome1** [comment] 2021-05-31 21:15
@nutnutwin, on your personal computer, could you at some point please 
1. switch yur OS to Chinese
2. delete sleeks config files (if you're using the zipped one from Github, just delete the "user-preferences.json" in that folder)
3. Start sleek and check if sleeks language detection is actually detecting your Chinese setup or if it falls back to English and has to setup to Chinese manually

**Comment by nutnutwin** [comment] 2021-05-31 21:35
@ransome1 something to share
I tried using sleek(out of box, just switched to SC) on
- 2 personal PC(English/English+SC package)
- 2 business PC(definitely English Clean Install)
they all show font fallback problems
so it has to be my tweak problem...

as for your request: 
"switch your OS to Chinese" means installing Chinese Language Package on English Windows, and set as UI language?
or Re-Install as SC?

Thank you

**Comment by ransome1** [comment] 2021-05-31 21:58
I think switching to a Chinese language pack should be fine. As soon as Windows shows Chinese signs instead of English letters, the language autodetection should trigger. But this only works if sleeks config is being deleted before starting.

**Comment by nutnutwin** [comment] 2021-05-31 21:59
@ransome1 
will do it later

**Comment by ransome1** [comment] 2021-05-31 22:12
No hurry, it's getting late here anyway ;)

**Comment by ransome1** [comment] 2021-06-01 07:26
@nutnutwin, SC has been released with https://github.com/ransome1/sleek/releases/tag/v1.0.5

**Comment by nutnutwin** [comment] 2021-06-01 10:36
@ransome1 Thank you. Just one problem, as is mentioned before, "Zoom" in "View" stay English
I didn't find entry in Translation.json
Not a big deal though

**Comment by ransome1** [comment] 2021-06-01 10:38
@nutnutwin, sorry I kind of missed this. I need to enhance this in the code. Can you provide the two translations here, so I can add them?

**Comment by nutnutwin** [comment] 2021-06-01 11:34
@ransome1 
- SC: "缩放"
- JP: "ズーム"(will add in jp/Translation.json) later

**Comment by ransome1** [comment] 2021-06-01 19:13
@nutnutwin, ok so here are the last entries that havn't been translated into any language besides English yet:
  "helpTabKeyboardSubtitle": "When add/edit todo window is open",
  "helpTabKeyboardTR13TD1": "Increase/decrease priority",
  "helpTabKeyboardTR14TD1": "Remove priority",
  "helpTabKeyboardTR15TD1": "Increase/decrease due date",
  "helpTabKeyboardTR16TD1": "Remove due date",
  "helpTabKeyboardTR17TD1": "Archive completed todo in done.txt"

Would be great if you could provide SC and JP.

**Comment by nutnutwin** [comment] 2021-06-02 14:17
"helpTabKeyboardSubtitle": "当显示新建/编辑任务窗口",  
"helpTabKeyboardTR13TD1": "增加/减少优先度",
"helpTabKeyboardTR14TD1": "移除优先度",
"helpTabKeyboardTR15TD1": "延后/提前到期日期",
"helpTabKeyboardTR16TD1": "移除到期日期",
"helpTabKeyboardTR17TD1": "将done.txt中已完成任务归档"

@ransome1 let me give you SC first

**Comment by nutnutwin** [comment] 2021-06-02 21:09
> 
> 
> @nutnutwin, on your personal computer, could you at some point please
> 
>     1. switch yur OS to Chinese
> 
>     2. delete sleeks config files (if you're using the zipped one from Github, just delete the "user-preferences.json" in that folder)
> 
>     3. Start sleek and check if sleeks language detection is actually detecting your Chinese setup or if it falls back to English and has to setup to Chinese manually

OK I did this exactly and the language detection didn't work, please see details below
- Start with English
- delete "user-preferences.json"
- Switch Display Language to SC
- signout/signin to take effect
- start sleek.exe
- stays English

JIC I tried downloading a fresh zip
[URL](https://github.com/ransome1/sleek/releases/download/v1.0.5/sleek-1.0.5-win.zip)
nothing changed

need some kind of log? (might be human error though)

**Comment by ransome1** [comment] 2021-06-03 05:20
I think the issue is, that the language detection modules was expecting a locale starting with "cn", but is propably getting "zn" (this is the default locale on OS set to Chinese, right?) delivered from your OS. 

I reuploaded the zipped version which is now setup for "zn": https://github.com/ransome1/sleek/releases/download/v1.0.5/sleek-1.0.5-win.zip

Maybe you could give this a try.

**Comment by nutnutwin** [comment] 2021-06-04 23:04
@ransome1 
one more thing
just noticed I can sponser this project
Do please keep up with the great work

**Comment by ransome1** [comment] 2021-06-05 20:56
@nutnutwin, now that sleek is available in SC, we are basically able to widen the audience accordingly. As of now only a small percentage of sleeks users are Chinese and I wouldn't mind changing this. But I must admit, I have not a lot of knowledge on Chinese (open source) app distribution. Are you aware of important Chinese app platforms which might be interesting to focus on?

**Comment by ransome1** [comment] 2021-06-05 20:58
> > I think the issue is, that the language detection module was expecting a locale starting with "cn", but is propably getting "zn" (this is the default locale on OS set to Chinese, right?) delivered from your OS.
> > I reuploaded the zipped version which is now setup for "zn": https://github.com/ransome1/sleek/releases/download/v1.0.5/sleek-1.0.5-win.zip
> > Maybe you could give this a try.
> 
> did try
> 
> * got a clean download
> * switch the display language to SC
> * boot sleek.exe
> * sleek UI in SC
>   @ransome1

Just to double check: You are confirming that on your PC set to SC, a fresh copy of sleek (with no previous configuration file) is loading the Chinese translations on first app start, correct?

**Comment by nutnutwin** [comment] 2021-06-05 21:37
> 
> 
> > > I think the issue is, that the language detection module was expecting a locale starting with "cn", but is propably getting "zn" (this is the default locale on OS set to Chinese, right?) delivered from your OS.
> > > I reuploaded the zipped version which is now setup for "zn": https://github.com/ransome1/sleek/releases/download/v1.0.5/sleek-1.0.5-win.zip
> > > Maybe you could give this a try.
> > 
> > 
> > did try
> > 
> > * got a clean download
> > * switch the display language to SC
> > * boot sleek.exe
> > * sleek UI in SC
> >   @ransome1
> 
> Just to double check: You are confirming that on your PC set to SC, a fresh copy of sleek (with no previous configuration file) is loading the Chinese translations on first app start, correct?

Yes
> a fresh copy of sleek (with no previous configuration file)
I redownloaded, so I do not have to deal with configuration file(to avoid human error)
@ransome1

**Comment by nutnutwin** [comment] 2021-06-05 23:53
> 
> 
> @nutnutwin, now that sleek is available in SC, we are basically able to widen the audience accordingly. As of now only a small percentage of sleeks users are Chinese and I wouldn't mind changing this. But I must admit, I have not a lot of knowledge on Chinese (open source) app distribution. Are you aware of important Chinese app platforms which might be interesting to focus on?

I totally agree. 
Unfortunately, I have no expertise on publicizing/marketing apps to specific user group(OS Engineer here)
But I would take this chance to see who might be interested in text based ToDo management

(in my case, 
- dont have access to common apps in company
- hate company apps(GSuite/Outlook
- prefer text(easy to backup/snap, customizable

Might write a few blogs somewhere in SC platforms...it will take some time though

**Comment by ransome1** [comment] 2021-06-06 05:09
@nutnutwin, that would of course be amazing! But don't get me wrong, I don't want you to push into things you have no time for doing to. In fact with my initial question I was referring to Chinese app stores (in the likes of Snap Store, Windows Store, Flathub) or websites that mirror the Github (like SourceForge), that my European kind isn't aware of.

**Comment by nutnutwin** [comment] 2021-06-06 05:30
@ransome1 Great
I wasn't aware of your Timezone though, 
me in JST(+9hour from UTC)

**Comment by ransome1** [comment] 2021-07-21 10:04
@nutnutwin the last issue of this (Input placeholder and values were shorten) should be solved in https://github.com/ransome1/sleek/releases/tag/v1.1.0-rc.4

We might be finally able to close this issue :) Looking forward hearing your feedback.

**Comment by nutnutwin** [comment] 2021-07-28 21:30
<img width="403" alt="20210728_Wed -083008" src="https://user-images.githubusercontent.com/34512273/127398682-6e57a775-b2b9-43ad-8b8e-2c0e3b0349f1.png">

@ransome1 
I downloaded the version specified and it looked like this. 
Will try the newest one later
(sorry didn't see the notification

**Comment by ransome1** [comment] 2021-07-29 05:11
@nutnutwin is this Windows on your screenhsot?

If so could you double check the version? This is what the 1.1.0 looks like on my Windows 10 VM:
![image](https://user-images.githubusercontent.com/11188741/127435287-6075fab1-0258-49f4-a253-e68932a06475.png)

**Comment by nutnutwin** [comment] 2021-08-02 10:35
@ransome1 
https://github.com/ransome1/sleek/releases/download/v1.1.0/sleek-1.1.0-win.zip
I tried this one it worked

Thank you for the work so far

**Closed** 2021-11-14 13:15 UTC
Labels: feature request
