### ISSUE TITLE
File tabs

### ISSUE THREAD

**Issue by 9z0** [ransome1/sleek#189] opened 2021-07-02 12:44 UTC
I think sleek is mature enough that we can now have multiple todo.txt files open as tabs, instead of continuous switching/multiple windows.

---
Edit: Task list
- [x] Show filename only, even if files are not in relative folders.
- [x] no close confirmation
- [x] You currently can't close the current file.
- [x] Ctrl+W to close the current tab.
- [x] Max, min tab width.
- [x] Switching is a bit slow. Maybe don't unload other tab(s) from memory, at least not immediately.
- [x] Ctrl+tab/ ctrl shift tab to cycle through tabs.
- [x] **Don't remove closed file from recent files (the folder icon on the left strip).**
- [ ] Unclose recently closed tab (Ctrl+Shift+T).
- [ ] Can there be a way to reset current tab instead of the whole app?

Other ideas/maybe list/just for reference:
- ~An option for no confirmation on tab close.~ **declined**
- An option to always show tabs, even with 1 file.
- An option to exclude the ".todo.txt" from the name in the tab title.
- Some way to keep UI elements from shifting when switching between tabs and no tabs.
- Option to show full path vs filename in tab title.
- Ctrl+W shouldn't close the entire app, even if it is the last open file/tab.
- Customizable max/min tab width.

**Comment by ransome1** [comment] 2021-07-17 07:30
Hi @9z0, @asakura42, @zerodat. A first draft of a tab bar function to switch between files has been added to this pre release: https://github.com/ransome1/sleek/releases/tag/v1.1.0-rc.1

Please feel free to download this release and give it proper testing. 

There wasn't much information in your feature request @9z0 so I just did what I wanted to do ;)

The tab bar will only be shown either
- when more than 1 file is added to sleek
- when the File tabs toggle has been set to true (which is the default setting anyhow) in the view drawer

Files can be switched by keyboard shortcuts. Press 1 to 9 to switch between them in the order of the files array. If this clashed with something we can also add Ctrl to this, but as long as there is no issue, I would prefer it simple by justing pressing the numbers.

Pressing the numbers while only having added one file does provoke a JavaScript error in the background, which is already fixed locally.

**Comment by 9z0** [comment] 2021-07-17 08:55
> There wasn't much information in your feature request @9z0 so I just did what I wanted to do ;)

Well, I didn't expect it so soon, so I was just suggesting it in principle. But I am definitely happy! 👍


> The tab bar will only be shown either

Makes sense! A slight problem is the shifting UI elements when you move between "no tabs" (1 file) and "tabs" (2+). For example, the search bar moves up/down a bit, but it is a small issue and easily fixable (see below).


> Files can be switched by keyboard shortcuts.

Both num and Ctrl+num are working fine for me.

> @amariusz @9z0, as a non native English speaker, I wasn't quite sure if `File tabs` does refer to what users associate with this feature. If the name is odd, let me know.

I would suggest just "Tabs". SumatraPDF uses "Use tabs". If you want verbosity, you can use something like: "Show multiple Files as tabs".

Some suggested improvements (most of these can be config file options):

- [ ] An option to show filename only, even if files are not in relative folders.
- [ ] An option to exclude the ".todo.txt" from the name.
- [ ] no need for the "not really deleted on disk" message. It seems obvious to me.
- [ ] You currently can't close the current file.
- [ ] Ctrl+W should close the current tab, not the entire app, even if it is the last open file.
- [ ] Max, min tab width (preferably customizable). In my case, long file pathname means only 1-2 tabs are shown at a time.
- [ ] Ctrl+tab/ ctrl shift tab to cycle through tabs.
- [ ] An option for no confirmation on tab close.
- [ ] Don't remove closed file from recent files (the folder icon on the left strip).
- [ ] Switching is a bit slow. Maybe don't unload other tab(s) from memory, at least not immediately.

**Comment by amariusz** [comment] 2021-07-17 18:50
@ransome1 Just as a reminder, I'm not native English speaker. Similarly to @9z0 I think just `Tabs` is enough.

You may consider however if you want to use tabs only for separate todo.txt files. I suppose that opening filter queries / named views in tabs would be a neat feature. That mostly depends if user has whole system in single file or is using multiple small files.

**Comment by ransome1** [comment] 2021-07-19 09:25
> > There wasn't much information in your feature request @9z0 so I just did what I wanted to do ;)
> 
> Well, I didn't expect it so soon, so I was just suggesting it in principle. But I am definitely happy! 
> 
> > The tab bar will only be shown either
> 
> Makes sense! A slight problem is the shifting UI elements when you move between "no tabs" (1 file) and "tabs" (2+). For example, the search bar moves up/down a bit, but it is a small issue and easily fixable (see below).

I don't think this is an issue as it can be expected.

> I would suggest just "Tabs" or "Enable tabs". [SumatraPDF](https://www.makeuseof.com/wp-content/uploads/2020/09/pdf-history-sumatrapdf.png) uses "Use tabs". If you want verbosity, you can use something like: "Show multiple files as tabs".

Tabs sounds good
 
> Some suggested improvements (most of these can be config file options):
> 
> * [ ]  An option to show filename only, even if files are not in relative folders.
> * [ ]  An option to always show tabs, even with 1 file.
> * [ ]  An option to exclude the ".todo.txt" from the name in the tab title.
> * [ ]  no need for the "not really deleted on disk" message. It seems obvious to me.

I agree, I removed the confirmation in general
> * [ ]  An option for no confirmation on tab close.
> * [ ]  You currently can't close the current file.
This is possible with the next release
> * [ ]  Ctrl+W should close the current tab, not the entire app, even if it is the last open file.
This too is part of the next release
> * [ ]  Max, min tab width (preferably customizable). In my case, long file pathname means only 1-2 tabs are shown at a time.

Besides the customizability this is added in the next release
> * [ ]  Ctrl+tab/ ctrl shift tab to cycle through tabs.

Also added
> * [ ]  Don't remove closed file from recent files (the folder icon on the left strip).

I understand your point, but prefer it like it is right now
> * [ ]  Switching is a bit slow. Maybe don't unload other tab(s) from memory, at least not immediately.

This puzzles me, as I can neither reproduce it nor should it happen, as it is the same function than switching files in the file switch window. 

As for the rest unfortunately I can't work on it as I don't see a big value but significant development hours in implementing all those options. If you want this customizability you might better fork sleek and attach these things.

> You may consider however if you want to use tabs only for separate todo.txt files. I suppose that opening filter queries / named > views within the same file in tabs would be a neat feature.

@amariusz I think I don't really understand what exactly you mean by that. Could you please rephrase it por moi? ;)

**Comment by ransome1** [comment] 2021-07-19 10:15
The next build is available :)
https://github.com/ransome1/sleek/releases/tag/v1.1.0-rc.3

**Comment by amariusz** [comment] 2021-07-20 05:17
> > You may consider however if you want to use tabs only for separate todo.txt files. I suppose that opening filter queries / named > views within the same file in tabs would be a neat feature.
> 
> @amariusz I think I don't really understand what exactly you mean by that. Could you please rephrase it por moi? ;)

Maybe an example would help. This is rather confliting use of tabs to the one you have implemented.

Let's assume `saved view` feature @zerodat mentioned is already present (https://github.com/ransome1/sleek/issues/193#issuecomment-878405886). User defined some views like  "Today", "Office", "Routines" (based on queries and sort order). What I meant was ability to open these in separate tabs.

**Comment by ransome1** [comment] 2021-07-20 06:00
@amariusz Ah ok now I understand, so the tab as a shell for a saved filters, but for the same file basically. Yeah that could also be an option, but I don't think it's what users would expect from a tab function in a simple app like sleek.

Though I think the `named view` idea of @zerodat could be combined with this somehow in the future. It could also be implemented as a list in an autocomplete like container (like the one that presents project and contexts when you add todos), that appears below the search field once a user focuses it. But that's a different story :)

**Comment by dlaidig** [comment] 2021-07-20 11:02
I have just tested 1.1.0-rc.3 via the AppImage and it immediately worked perfectly with the files I had already open. I really like that the number shortcuts make it extremely simple and fast to switch between files. :)

The only confusing aspect is that now I have two tabs with the titles "todo.txt" and "todo.txt", which is not very helpful. I can work with that as long as the tabs are in the order that I expect. This seems to be the order in which the files are opened, which is fine. But if I close the wrong file on accident, that means I have to close multiple files and carefully re-open them in the correct order. So there are two things I would find helpful:

1. A way to rename the tabs (e.g., by right-clicking on the tab). An alternative way would be some automatic strategy to create unique tab titles (e.g., add the parent folder to the title as long as there are duplicates) but I guess manual renaming is simpler and has many advantages (my path names are way less helpful than the titles I would pick manually).
2. A way to change the order of the tabs (of course, drag-and-drop is the natural way, but "move to start" and "move to end" in a context menu might be a lot easier to implement).

(Let me know if I should create individual issues for those aspects.)

**Comment by 9z0** [comment] 2021-07-20 12:58
- > .. shifting UI elements ...

More of an improvement! :)  It is a minor thing anyway.

---
- > I agree, I removed the confirmation in general

If it is not going to be optional, then perhaps a way to **unclose** (Ctrl+Shift+T).

---
- > Tab width

Now for me, all tabs show the early (often identical) path :)
```
|  C:\tasks\folder....  |  C:\tasks\folder....  |  C:\tasks\folder....  |
```
It should show the file name with the full path on hover. Maybe @amariusz's suggestion too.

---
- >Tab cycling

Ctrl+Shift+Tab works but Ctrl+Tab doesn't.

---
- > recent files

Well, there should be some way to access recent files. It is very annoying to have to navigate to closed files to re-open them every time. 😕

---
- >Slow switching.

I am not sure why but it takes perceptible time for me:

```
Success: Filters resetted
files.mjs:42 Info: Modal closed and cleaned up
files.mjs:76 Success: File selected
render.js:754 Table build: >200 ms
render.js:132 Info: Hide onboarding
render.js:754 Table build: >100 ms
render.js:132 Info: Hide onboarding
```

---
- > ... If you want this customizability you might better fork sleek and attach these things.

It is not very feasible for me unfortunately.

I think some of them are not too difficult? For example, hiding "todo.txt". You would know better than me anyway.

---
- [ ] Can there be a way to reset current tab instead of the whole app?

---
Thanks a lot for the other fixes!

**Comment by ransome1** [comment] 2021-07-21 06:20
https://github.com/ransome1/sleek/releases/tag/v1.1.0-rc.4

@dlaidig If you're working with more than one file called todo.txt this of course is an issue. A renaming context menu can be a useful enhancement on this. As would be the reordering. But as my time is very limited this can only be added in the future. Also I would like to understand first, if this feature is actually being utilized by sleeks users.

@9z0 there shouldn't be any file paths shown in the tabs, that was a Windows related glitch and is fixed in rc4

`Ctrl + Tab` and `Ctrl + Shift + Tab` work fine on my Linux machines and also on my Windows VM. I'm not sure what to do about this.

Also there has been an issue with the file tabbing, which led to the file getting loaded two times as you can see in your log. This is fixed in rc4. Though I'm still surprised why the first table built took more than 200ms. I assume you have a very large screen resolution maybe? If so the amount of todos loaded at once will be higher and could lead to these times. And no, I'm not going to work on any options ;)

As for the rest, this is as good as it gets for this prototype. Now I want to understand if there is any usage at all and if there will be feedback on this.

So please let me know if there are any further major issues. 

@9z0 : Btw. I'm counting more than 10 single requirements that popped up over the course of this thread. And your initial request consists of one sentenced. This will of course always lead to a significant gap between whatever you're having in mind and what's going to be developed ;)

**Comment by dlaidig** [comment] 2021-07-21 08:56
> @dlaidig If you're working with more than one file called todo.txt this of course is an issue. A renaming context menu can be a useful enhancement on this. As would be the reordering. But as my time is very limited this can only be added in the future. Also I would like to understand first, if this feature is actually being utilized by sleeks users.

I would guess that multiple "todo.txt" files are not a uncommon use case, since in most applications the file names (at least "done.txt", for example in sleek...) are fixed and "todo.txt" is the standard name in the original CLI tool. So in order to separate multiple lists (in my case, personal and work), using different directories makes sense.

But I do understand that those ideas are not essential. I might create a feature request at some point. :)

> @9z0 there shouldn't be any file paths shown in the tabs, that was a Windows related glitch and is fixed in rc4
> 
> `Ctrl + Tab` and `Ctrl + Shift + Tab` work fine on my Linux machines and also on my Windows VM. I'm not sure what to do about this.

For me (testing via Linux AppImage), `Ctrl + Tab` and `Ctrl + Shift + Tab` work, but only if I hold down `Ctrl` for an unusually long amount of time. I almost wanted to write that it does not work at all, but then I noticed it working when I pressed `Tab` multiple times... Maybe that explains the different observations.

**Comment by ransome1** [comment] 2021-07-21 09:04
That's interesting, thanks for this detail, maybe I'll find some glitch somewhere.

@9z0 can you confirm @dlaidig observation also on your side?

**Comment by 9z0** [comment] 2021-07-21 13:57
> @9z0 there shouldn't be any file paths shown in the tabs, that was a Windows related glitch and is fixed in rc4

Confirmed. Thanks

> `Ctrl + Tab`

It works with the right Ctrl but not the left one !!

I can also reproduce @dlaidig's finding but with a variation: the trick for me was to release "tab" before releasing "ctrl" (which you are likely to do subconsciously if you are holding the ctrl button for long). Again, this is not needed with the right ctrl button.

This is also similar to the (now fixed) [issue with ctrl+enter](145#issuecomment-859053746).


> Also there has been an issue with the file tabbing, which led to the file getting loaded two times as you can see in your log. This is fixed in rc4.

Confirmed. Faster now. 👍

>Though I'm still surprised why the first table built took more than 200ms. I assume you have a very large screen resolution maybe? If so the amount of todos loaded at once will be higher and could lead to these times.

Screen resolution is not big but I have > 1000 todos and many dozens of projects/contexts.

>And no, I'm not going to work on any options ;)

😔


> @9z0 : Btw. I'm counting more than 10 single requirements that popped up over the course of this thread. And your initial request consists of one sentenced. This will of course always lead to a significant gap between whatever you're having in mind and what's going to be developed ;)

I totally get that people have different expectations and usage patterns. I will probably open a discussion about to understand your position better.

**Comment by ransome1** [comment] 2021-07-25 05:43
@9z0 you can take a look at the latest RC, which will preserve the file history when closing tabs: https://github.com/ransome1/sleek/releases/tag/v1.1.0-rc.5

I think I once stumbled upon a glitch, but weren't able to see it again. It's a minor enancement with significant changes to the code, so let me know if you find something odd about this.

**Comment by dlaidig** [comment] 2021-07-25 10:35
There does seem to be some quite fundamental glitch in rc5:

I quickly wanted to test if v1.1.0-rc.5 fixes #220 and created a new temporary two-line todo.txt file with a text editor (`/home/user/temp/todo.txt`). I already had my real todo file open (lets call it `/home/user/important/todo.txt`) and when I opened the temporary todo file, it created a new tab. (Also, the `@call +dad` task was now visible). So far so good.

However, marking any of the two test tasks as done did not seem to have any effect. Checking the javascript console, I saw
~~~
Success: Changes written to file: /home/user/important/todo.txt
~~~
and indeed, `/home/user/important/todo.txt` was overwritten with the contents of `/home/user/temp/todo.txt`.

(I do seem to have some talent in finding such issues :sweat_smile:)

**Comment by ransome1** [comment] 2021-07-25 10:41
I was trying to somehow reproduce this the way you described it, but without any success. I'm going to take a look at it later again. If you have more detail on this, let me know.

**Comment by dlaidig** [comment] 2021-07-25 10:53
One minor detail that might help: I just noticed that with rc5 and the temporary file open, I had the following entries in `user_preferences.json`:

`"path":"/home/user/temp","file":"/home/user/important/todo.txt"`

When starting rc4 again and selecting the temporary tab:

`"path":"/home/user/temp","file":"/home/user/temp/todo.txt"`

(Sorry for the off-topic question: Is there a way to disable the AppImage auto update or at least to prevent it from automatically deleting the old version without asking? I found this behavior quite surprising and only understood what is going on by looking at the command line output...)

**Comment by ransome1** [comment] 2021-07-26 06:09
@dlaidig I think I might have found the cause for this behavior. The `file` option in `user-preferences.json` has been deprecated in rc.5 and therefor not updated when you added a new file. But it was still used in 2 functions which might have let to this issue.

Could you please check https://github.com/ransome1/sleek/releases/tag/v1.1.0-rc.6 and try to exactly reproduce the issue one more time the you did it yesterday?

As for the AppImage there is no way to disable in the current state of sleek. But I can easily introduce a hidden setting for this. I don't consider the auto update an issue. But it is an issue if the updater is bumping up from a proper release to a pre-release, which I will need to check and disable.

**Comment by dlaidig** [comment] 2021-07-26 08:00
I can confirm that the issue seems fixed in rc.6. I also reproduced the issue in rc.5 again directly before switching to rc.6 and rc.6 updated the correct file. :)

Btw, I do quite like that the tab order now seems to be based on the order of the "recent files" entries. This makes it so much faster to restore a consistent tab order after accidentally closing a tab (and that really happened a few times already).

I would appreciate a hidden setting to disable AppImage updates. Still, it might be worth to consider at least not deleting the old version automatically. After some times, I also noticed that there is a notification, but it disappears too fast for me to notice it most of the time. I also noticed that the auto update does not follow most of the [recommendations on appimage.org](https://docs.appimage.org/packaging-guide/optional/updates.html#recommended-user-experience) ("Never download updates without the user’s explicit consent") and even re-downloads and overwrites existing files on every startup.

**Closed** 2021-07-26 19:38 UTC
Labels: call for testing, feature request

**Comment by 9z0** [comment] 2021-07-26 19:47
I can confirm @dlaidig's finding (write to wrong file) in rc5 on Windows. I will check rc6 to see if fixed.

I added a request to open multiple instances of the same file in tabs. For example, to view multiple filters at the same time.

Thanks a lot for the recent history. I think tabs are in a good condition so I closed this issue; minor requests/improvements notwithstanding. :)
